### ISSUE TITLE
Cooking_Oven_Status_CurrentCavityTemperature not refreshed

### ISSUE THREAD

**Issue by wired-ed** [iobroker-community-adapters/ioBroker.homeconnect#1]
Hi dna909,

Awesome project, thanks a ton for building this!

Just one question/ observation: while I can read Cooking_Oven_Status_CurrentCavityTemperature (e.g. with jarvis on top of ioBroker), this property does not seem to get refreshed. It will only update when I restart the instance of the homeconnect adapter. All other properties I have tried do get refreshed.

Is there a chance to fix that (or a workaround)? That would be great! Or is it a problem with the Home Connect API? 

Best regards
Jan

**Comment by Morluktom** [comment]
I think a polling function for the status request is not a good idea. 
This will generate a lot of traffic on the home connect server.

**Comment by SurfGargano** [comment]
That is maybe the reason it is not an event. But I have no idea to get the temperature otherwise. Maybe polling only if the oven is in use ?

**Comment by Morluktom** [comment]
For me the implementation of the API is not conclusive. If you compare this point with the door. With the status request you get the current status of the door. If you open or close the door you get a event. For me, the implementation for the CurrentCavityTemperature should be identical. I think this is an API bug
