### ISSUE TITLE
The rate limit "1000 calls in 1 day" was reached. Restarting....

### ISSUE THREAD

**Issue by tnowak** [iobroker-community-adapters/ioBroker.homeconnect#10]
Adapter worked fine for several months, but I get this error every 5 minutes now:

```
homeconnect.0 | 2021-02-21 18:26:33.658 | warn | (28191) Restart initiated-
homeconnect.0 | 2021-02-21 18:26:31.664 | warn | (28191) Retry Refresh Token in 5min
homeconnect.0 | 2021-02-21 18:26:31.663 | error | (28191) Error Refresh-Token: 403 undefined
homeconnect.0 | 2021-02-21 18:26:31.656 | warn | (28191) Restart the Adapter to get all devices correctly.
homeconnect.0 | 2021-02-21 18:26:31.654 | error | (28191) Error getting Aplliances with existing Token: 429 The rate limit "1000 calls in 1 day" was reached. Requests are blocked during the remaining period of 31468 seconds.
```

I've already changed token to a new one.
Any ideas what happened?

**Comment by TA2k** [comment]
This happens when the adapter restarts too often

**Comment by tnowak** [comment]
But my adapter doesn't restart at all (at least didn't before). Now it restarts because of that rate limit. Is this rate limit a new thing? Why do my adapter hits it anyway?

**Comment by TA2k** [comment]
It restarts because of an invalid refresh token.

**Comment by tnowak** [comment]
I've replaced Client ID and token to new one yesterday and its the same after some time.
I will do it again now, but I doubt it will help

**Comment by tnowak** [comment]
Right now I'm not even getting Activation URL out of Client ID :/

**Comment by tnowak** [comment]
Ok, solved it by removing instance. Created new and new token used. Proof:

```
homeconnect.0 | 2021-02-22 12:58:30.832 | info | (2948) BOSCH-WAVH8K90PL-68A40E2F0B70: There is no program active
homeconnect.0 | 2021-02-22 12:58:19.756 | info | (2948) BOSCH-WAVH8K90PL-68A40E2F0B70: There is no program active
homeconnect.0 | 2021-02-22 12:58:15.256 | info | (2948) Accesstoken renewed...
homeconnect.0 | 2021-02-22 12:58:14.720 | info | (2948) starting. Version 0.0.32 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v12.19.0, js-controller: 3.1.6
```

Let's see how it works now.

**Comment by tnowak** [comment]
Guess what.


```
homeconnect.0 | 2021-02-22 13:21:00.274 | warn | (1106) Restart initiated
homeconnect.0 | 2021-02-22 13:20:58.374 | warn | (1106) Retry Refresh Token in 5min
homeconnect.0 | 2021-02-22 13:20:58.373 | error | (1106) Error Refresh-Token: 401 undefined
homeconnect.0 | 2021-02-22 13:20:58.273 | warn | (1106) Restart the Adapter to get all devices correctly.
homeconnect.0 | 2021-02-22 13:20:58.270 | error | (1106) Error getting Aplliances with existing Token: 429 The rate limit "1000 calls in 1 day" was reached. Requests are blocked during the remaining period of 49803 seconds.

```

So brand new token worked for like 15 minutes.......

**Comment by TA2k** [comment]
You should stop the adapter for 1 day

**Comment by tnowak** [comment]
Ok, I will.

**Comment by tnowak** [comment]
You were right, using new Token after 24h = no problems with the adapter. Perheps adapter's token refresh procedure might need some investigation.

**Comment by OberfragGER** [comment]
> You were right, using new Token after 24h = no problems with the adapter. Perheps adapter's token refresh procedure might need some investigation.

Did you set up a new appliance in homeconnect?
Hav ethe same problem. Was working for an long time but now i reach daily the 1.000 API calls!

**Comment by aDabbelju** [comment]
I have the same problem with to many api-calls. Deactivating the adapter for one day heals a few days. Now i have the same problem. I´m using this adapter for a Siemens EQ9 connect coffee machine.
