### ISSUE TITLE
Error AuthUriGet: 400

### ISSUE THREAD

**Issue by ronschd** [iobroker-community-adapters/ioBroker.homeconnect#11]
Hallo,

nach dem Eintragen der ClientID --> Schließen & Speichern, taucht folgender Eintrag im Log auf.

Error AuthUriGet: 400

Beim erneuten Öffnen ist die Zeile mit der Activation URL leer.

lg R

**Comment by TA2k** [comment]
Einfach kurz geduld haben. Adapter muss zweimal neustarten

**Comment by ronschd** [comment]
Okok, danke.
Macht er das von selbst ?
hat nämlich immer noch keine Activation URL.

lg R

**Comment by swisswn** [comment]
@ronschd Hallo. Hast du eine Lösung gefunden für das Problem. Ich bekomme leider auch keine Activation URL.

**Comment by ronschd** [comment]
@swisswn leider nein.
Funktioniert bei mir immer noch nicht.

**Comment by swisswn** [comment]
@ronschd Bei funktioniert es jetzt. Einfach genau nach Anleitung hier im Wiki vorgehen!

**Comment by ronschd** [comment]
@swisswn 
Habs jetzt nochmal gemacht.
Ich dürfte irgendwo einen Fehler gemacht haben, jetzt funktionierts, danke !
