### ISSUE TITLE
State changes and state values

### ISSUE THREAD

**Issue by Claus1985** [iobroker-community-adapters/ioBroker.homeconnect#12]
Hi Guys,

thx for the great adapter!
Im still new to ioBroker and was using fhem for controlling my dishwasher. Now I want to switch to ioBroker using this adapter.

Installation was easy and I got all the states of my dishwasher in objects of ioBroker. Now what I don’t get is how to implement state changes in a blockly Script. I tried changed and updated as trigger event for door state and machine state (ready, inactive, etc.) like this:

![88128798-EAF9-4E60-ABD1-940B9692BE2C](https://user-images.githubusercontent.com/69499563/111516989-dd049600-8754-11eb-90a4-018199f90cbc.jpeg)

But Problem is the event does not trigger. Only trigger working is changed for remote control (Fernstart).

What do I have to do to use trigger with door and machine state?
And can I just use states like Open and Close or do I have to use the whole string including machine type etc? And if so in which format?

thx and brgds,

Claus

**Comment by TA2k** [comment]
Ich bin nich so fit in blockly is eher eine Forum frage
