### ISSUE TITLE
Geschirrspüler startet nach Spülen erneut :(

### ISSUE THREAD

**Issue by Skol6** [iobroker-community-adapters/ioBroker.homeconnect#127]
Hi,

ich hab ein kleines Blockly-Script geschrieben mit dem ich den Geschirrspüler starten kann wenn z.b. der Strompreis niedrig ist.
**Zum Starten des Programps setze ich:**
- Prüfen ob status.BSH_Common_Status_RemoteControlStartAllowed = True 
- Setzen von programs.active.BSH_Common_Root_ActiveProgram =programs.selected.BSH_Common_Root_SelectedProgram

**Problem:**
Blöd ist nur wenn er mit dem Programm fertig ist, dann startet er das Programm erneut.
Sollte sich der Wert BSH_Common_Status_RemoteControlStartAllowed nach dem Spülen nicht automatisch wieder zurücksetzen?
Ich probiere es mal mit manuellem Zurücksetzen.

**Blockly:**
![image](https://github.com/iobroker-community-adapters/ioBroker.homeconnect/assets/94216949/10c7dc10-b558-4401-a869-d21f5dd84097)

Wo könnte den da der Hund begraben sein?

**Zweiter Punkt der Eigenartig ist:**
Beim Geschirrspüler erscheint manchmal das Symbol für "Remote Start" am Boden und manchmal nicht.
Der Status ist aber immer gesetzt wenn ich die Taste am Geschirrspüler drücke und auch im Adapter entsprechend gesetzt.

**Comment by TA2k** [comment]
Das sind eher fragen für den API Anbieter
https://developer.home-connect.com/support/contact

**Comment by Skol6** [comment]
Rückmeldung ist bisher noch eher dünn.
Den Status bekommt man darüber bzw. ob der Geschirrspüler fertig ist: [https://api-docs.home-connect.com/states/#operation-state](https://api-docs.home-connect.com/states/#operation-state)

**Comment by Skol6** [comment]
Also:
- Wie es scheint gibt es einen Bug in der Geschirrspülersoftware.
- Der Status BSH.Common.EnumType.OperationState.Finished wird leider nur für 5sec auf "TRUE" getriggert, dann geht er wieder auf "READY"
- Ich hab das mit einer zusätzlichen Variable gelöst die einen Neustart solange blockiert, bis der Geschirrspüler wieder geöffnet wurde.
- Lt. BSH Service Kontakt - developer@Home-Connect.com - haben sie hier ein Update eingeplant, nur keiner weiß wann das kommt

Workarround:
![image](https://github.com/iobroker-community-adapters/ioBroker.homeconnect/assets/94216949/b825e693-81f3-44b1-babe-bad72062305f)

+
![image](https://github.com/iobroker-community-adapters/ioBroker.homeconnect/assets/94216949/ba74e824-2fe4-48cc-8e09-bcb2599adf59)
