### ISSUE TITLE
Fehlende Objekte

### ISSUE THREAD

**Issue by nob0dy80** [iobroker-community-adapters/ioBroker.homeconnect#15]
Hallo,
ich habe meine Siemens Spülmaschine gerade integriert und es funktioniert soweit auch alles.
Allerdings bekommen ich beim Start des Adapters eine Meldung über fehlende Objekte:

`homeconnect.0	2021-04-16 09:58:52.897	warn	(731) State "homeconnect.0.xxxxxxxxxxxxxxxxxxxxx.programs.selected.options.Eco50.Dishcare_Dishwasher_Option_SilenceOnDemand" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-04-16 09:58:52.896	warn	(731) State "homeconnect.0.xxxxxxxxxxxxxxxxxxxxx.programs.selected.options.Eco50.Dishcare_Dishwasher_Option_VarioSpeedPlus" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-04-16 09:58:52.894	warn	(731) State "homeconnect.0.xxxxxxxxxxxxxxxxxxxxx.programs.selected.options.Eco50.Dishcare_Dishwasher_Option_IntensivZone" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-04-16 09:58:52.894	warn	(731) State "homeconnect.0.xxxxxxxxxxxxxxxxxxxxx.programs.selected.options.Eco50.Dishcare_Dishwasher_Option_HygienePlus" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-04-16 09:58:52.894	warn	(731) State "homeconnect.0.xxxxxxxxxxxxxxxxxxxxx.programs.selected.options.Eco50.BSH_Common_Option_StartInRelative" has no existing object, this might lead to an error in future versions`

Wenn ich in den Objektbaum schaue, scheinen diese Objekte aber alle da zu sein:

![image](https://user-images.githubusercontent.com/28686079/114992362-f6efe080-9e9a-11eb-9c85-d9778bf6174f.png)

Kann mir jemand sagen wie ich damit umgehen soll?

Vielen Dank

**Comment by TA2k** [comment]
erstmal ignorieren wird in zukünfitgen version behoben

**Comment by stenmic** [comment]
wann wird es eine neue Version geben?
