### ISSUE TITLE
Neff Backofen sofort gefunden , Constructa Spülmaschine leider nicht

### ISSUE THREAD

**Issue by Mar-Wey** [iobroker-community-adapters/ioBroker.homeconnect#16]
Hallo zusammen,

ich habe den Homeconnect Adapter 0.0.332 installiert und läuft soweit.

Ich habe Zugrif auf unseren Neef Backofen, jedoch leider nicht auf unsere Constructa Spülmaschine oder Bosch Wama .. :-( ..

Was muss ich bitte wie durchführen, das mehr als ein Gerät angezeigt und somit bedienbar wird.

Vielen dank für Eure Feedback.

Viele Grüße,
MarWey

**Comment by TA2k** [comment]
Sind denn alle Geräte in der Homeconnect App sichtbar?

**Comment by Mar-Wey** [comment]
Guten Morgen TA2K,
ja sind sie .... Alle drei .... Aber lediglich den Zgriff & Anzeige des neef backofens ist im IOBroker zu sehen .... :-( 

Irgendwo habe ich gelesen , dass es wohl in der "Privatfunktion" bei Homeconnect nur ein Gerät zulässt ???

ich weiss es einfach nicht , alle Geräre in der App und laufen wie bolle, nur im IOBroker incl. App leider nicht ... :-(

Grüße,
MarWey

**Comment by TA2k** [comment]
Ich habe auch keine Idee normalerweise sind alle Geräte immer sichtbar. Vielleicht den Adapter neuinstallieren und den token zurücksetzen

**Comment by Mar-Wey** [comment]
Hallo TA2K,
ich habe den token zurück gesetzt ... leider nichts ....
Nun installiere ich alles einmal neu ....
Gibt es eigentlich auch eine How to Do in Deutsch .... Anleitung / FAQ wonach Mann einfach vorgehen könnte ???
Grüße,
MarWey

**Comment by Mar-Wey** [comment]
Sodele, nochmals alles neu installiert --> wieder nur der Backofen ! :-( 
Kein Spülmaschine & keine Wama ! :-( 
Hmmm ....
Jemand vielleicht noch eine Idee ??
Grüße,
MarWey

**Comment by arteck** [comment]
in der app siehst du die ?? und sind die Fernsteuerbar ?
