### ISSUE TITLE
Siemens Dishwasher not connecting since one week

### ISSUE THREAD

**Issue by andiweli** [iobroker-community-adapters/ioBroker.homeconnect#173]
**Describe the bug**  
Siemens Dishwasher not connecting since a few days.
Last connected state was last week.
Adapter status is green, no other issues in ioBroker.

**Expected behavior**  
Connection established and syncing the current states.

**Versions:**  
 - Adapter version: 1.4.1
 - JS-Controller version: 5.0.19
 - Node version: 18.20.4
 - Operating system: Raspberry OS Lite 64 Bit

**Additional context**  
No Errors shown in log.

Dishwasher is connected to WiFi and online in the Home Connect app.
I can control the device without problems thru the official Home Connect app.

**Comment by mcm1957** [comment]
Please add a debug log.

**Comment by andiweli** [comment]
That's what I am getting now...

homeconnect.0 | 2024-07-26 08:09:54.910 | error | {"error":{"description":"HomeAppliance is offline","key":"SDK.Error.HomeAppliance.Connection.Initialization.Failed"}}
-- | -- | -- | --
homeconnect.0 | 2024-07-26 08:09:54.909 | error | AxiosError: Request failed with status code 409
homeconnect.0 | 2024-07-26 08:09:47.986 | error | {"error":{"description":"HomeAppliance is offline","key":"SDK.Error.HomeAppliance.Connection.Initialization.Failed"}}
homeconnect.0 | 2024-07-26 08:09:47.983 | error | AxiosError: Request failed with status code 409

**Comment by mcm1957** [comment]
This looks like a problem at Home Connect Services.
The adapter received error 409 and the message "HomeAppliance is offline". So the adapter can obviously communicate with the home connect webservice. Why the supplier api retunr offline is oiut of control for the adapter.

But please attach a log with level DEBUG - eventually some more info is visible there,

**Comment by andiweli** [comment]
Hmm that is with debug enabled and log copypaste...

2024-07-25 19:22:22.567 - error: homeconnect.0 (2136) AxiosError: Request failed with status code 409
2024-07-25 19:22:22.575 - error: homeconnect.0 (2136) {"error":{"description":"HomeAppliance is offline","key":"SDK.Error.HomeAppliance.Connection.Initialization.Failed"}}
2024-07-25 19:22:26.900 - error: homeconnect.0 (2136) AxiosError: Request failed with status code 409
2024-07-25 19:22:26.901 - error: homeconnect.0 (2136) {"error":{"description":"HomeAppliance is offline","key":"SDK.Error.HomeAppliance.Connection.Initialization.Failed"}}

**Comment by mcm1957** [comment]
Hmm - would have expected more info...
But thanks for attaching the log

**Comment by andiweli** [comment]
Today I again had this in the log...

2024-07-30 14:29:34.694 - error: homeconnect.0 (28224) AxiosError: Request
failed with status code 409
2024-07-30 14:29:34.697 - error: homeconnect.0 (28224)
{"error":{"description":"HomeAppliance is
offline","key":"SDK.Error.HomeAppliance.Connection.Initialization.Failed"}}
2024-07-30 14:30:09.501 - error: homeconnect.0 (28224) AxiosError: Request
failed with status code 409
2024-07-30 14:30:09.502 - error: homeconnect.0 (28224)
{"error":{"description":"HomeAppliance is
offline","key":"SDK.Error.HomeAppliance.Connection.Initialization.Failed"}}

Am Mo., 29. Juli 2024 um 23:46 Uhr schrieb Martin M. <
***@***.***>:

**Comment by andiweli** [comment]
Today the adapter received data again. I assume it was some server side bug.

**Comment by mcm1957** [comment]
Thanks for Info.

Ithink we can close here. Please comment or open a new issue if you feel that a Bug at the adapter exists
