### ISSUE TITLE
Washer program options doesn't work

### ISSUE THREAD

**Issue by HackyPaddy** [iobroker-community-adapters/ioBroker.homeconnect#174]
**Describe the bug**  
The adapter gets the data points from the program, but many of them cannot write. Especially the options like water plus, vario speed, etc.

**Screenshots & Logfiles**  
Error in Log...

homeconnect.0 | 2024-07-29 22:30:57.224 | error | {"error":{"description":"Program option not supported","key":"SDK.Error.UnsupportedOption"}}
-- | -- | -- | --
homeconnect.0 | 2024-07-29 22:30:57.223 | error | AxiosError: Request failed with status code 409

**Versions:**  
 - Adapter version: 1.4.1
 - JS-Controller version: 5.0.19
 - Node version: 18.20.4
 - Operating system: Debian Bullseye, Raspberry 64-bit

**Comment by mcm1957** [comment]
Error looks like homeconnect api (not the adapter) does not support the desired function.

API specifies for code 409:
Command/Query cannot be executed for the home appliance, the error response contains the error details

Error Datails are Program option not supported

So this does not look like anything the adapter can change..

But please attach a DEBUG LOG to see more details.

**Comment by HackyPaddy** [comment]
I just read the API documentation myself and as you said, this feature is not supported.
Big crap from BSH...

Who sets only the temperature and spin speed? It's the program-options that make things interesting.

Someone should understand that...
