### ISSUE TITLE
program not available

### ISSUE THREAD

**Issue by arteck** [iobroker-community-adapters/ioBroker.homeconnect#19]
das ist die Spülmaschiene

![grafik](https://user-images.githubusercontent.com/6681528/121144851-a6fc1d00-c83e-11eb-9e60-1f13f41d15fb.png)

das muss anders gehen..wenn ein Programm nicht verfügbar ist oder nicht gesendet wird ...

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/121145667-78cb0d00-c83f-11eb-81c4-24cc83426aa8.png)

**Comment by TA2k** [comment]
Was ist genau das Problem? Das ist die Meldung die die API zurück gibt
https://api-docs.home-connect.com/undefined/?#api-errors

**Comment by arteck** [comment]
das Problem ist wie du siehst, dass danach die Schnitstelle blokiert wird für minuten.. 
`The rate limit "10 successive error calls in 10 minutes" was reached. Requests are blocked during the remaining period of 439 seconds.`

und komisch ist das die APP dass nicht meldet..

**Comment by TA2k** [comment]
Die App ist komplett unterschiedliche zur API.
Wie sieht das Verhalten im debug mode aus?

**Comment by arteck** [comment]
ich hab ein wenig weiter analysiert 
wenn die Kaffemaschiene eingeschaltet wird
![grafik](https://user-images.githubusercontent.com/6681528/130313161-fed7d9d6-97cb-4f62-bed1-66bcdfa1061c.png)

danach gehts mit den timeouts los
