### ISSUE TITLE
Please update the logo as actual one is outdated

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.homeconnect#20]
https://developer.home-connect.com/sites/all/themes/bsh_hc/assets/images/hc-logo.svg

You may use this one and we have official permission to use it.
![image](https://user-images.githubusercontent.com/4582016/121420746-ba59d600-c96d-11eb-9c6e-ae45103ec662.png)

**Comment by TA2k** [comment]
updated
