### ISSUE TITLE
API temporarily unavailable

### ISSUE THREAD

**Issue by ChristophsMowL** [iobroker-community-adapters/ioBroker.homeconnect#202]
Does Homeconnect use a new API or is this temporarily?

**Versions:**  
 - Adapter version: homeconnect 1.4.1
 - JS-Controller version: 6.0.11
 - Node version: 20.17
 - Operating system: docker 9.1.2

![Unbenannt](https://github.com/user-attachments/assets/1ec63c4e-e1b9-4763-abf7-1874059c089a)

**Comment by capitaenz** [comment]
The official app on IOS no longer works either.

**Comment by Horgul123** [comment]
Can confirm this issue.
The Android app is working-

In gerneral:
There should be a mechanism which slows down the error messages in the log if there is an error for a longer time.

**Comment by andre-bu** [comment]
Can confirm.
The Android app is working

**Comment by mcm1957** [comment]
The api is currently not available.
See errorocode 503 - Service TEMPORARELY not available.

Please check forum:
https://forum.iobroker.net/topic/77542/homeconnect-keine-verbindung-mehr/4
