### ISSUE TITLE
Bosch vacuum robot cause adapter to crash 

### ISSUE THREAD

**Issue by Maverick78de** [iobroker-community-adapters/ioBroker.homeconnect#205]
the Bosch vacuum robot (BCR1ACDE/03) cause the adapter to crash in loop until iobroker detects loop restarts

This always happens if a active program ist running. 
I use this device in ioBroker only for vis, no scripts are involved.

Adapter version 1.4.1

`
host.iobroker | 2024-10-23 20:21:15.719 | info | Restart adapter system.adapter.homeconnect.0 because enabled
-- | -- | -- | --
host.iobroker | 2024-10-23 20:21:15.718 | error | instance system.adapter.homeconnect.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2024-10-23 20:21:15.718 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.homeconnect/main.js:665:24
host.iobroker | 2024-10-23 20:21:15.718 | error | Caught by controller[1]: at Homeconnect.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7720:21)
host.iobroker | 2024-10-23 20:21:15.718 | error | Caught by controller[1]: at Homeconnect._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7749:29)
host.iobroker | 2024-10-23 20:21:15.718 | error | Caught by controller[1]: at Validator.validateSetStateObjectArgument (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:422:19)
host.iobroker | 2024-10-23 20:21:15.718 | error | Caught by controller[1]: Error: The state contains the forbidden properties x, y!
host.iobroker | 2024-10-23 20:21:15.717 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
homeconnect.0 | 2024-10-23 20:21:15.002 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
homeconnect.0 | 2024-10-23 20:21:15.000 | info | terminating
homeconnect.0 | 2024-10-23 20:21:14.969 | error | The state contains the forbidden properties x, y!
homeconnect.0 | 2024-10-23 20:21:14.968 | error | Error: The state contains the forbidden properties x, y! at Validator.validateSetStateObjectArgument (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:422:19) at Homeconnect._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7749:29) at Homeconnect.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7720:21) at /opt/iobroker/node_modules/iobroker.homeconnect/main.js:665:24
homeconnect.0 | 2024-10-23 20:21:14.799 | error | unhandled promise rejection: The state contains the forbidden properties x, y!
homeconnect.0 | 2024-10-23 20:21:14.798 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
homeconnect.0 | 2024-10-23 20:21:12.799 | info | BOSCH-BCR1ACDE-68A40E5666A9/programs/active: There is no program active.
homeconnect.0 | 2024-10-23 20:21:12.789 | info | BOSCH-BCR1ACDE-68A40E5666A9/programs/active/options: There is no program active.
homeconnect.0 | 2024-10-23 20:21:12.326 | info | No array: selected
homeconnect.0 | 2024-10-23 20:21:12.319 | info | No array: active
homeconnect.0 | 2024-10-23 20:21:11.226 | info | Found 2 devices
homeconnect.0 | 2024-10-23 20:21:09.512 | info | starting. Version 1.4.1 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v20.18.0, js-controller: 6.0.11
host.iobroker | 2024-10-23 20:21:05.461 | info | instance system.adapter.homeconnect.0 in version "1.4.1" started with pid 85038
host.iobroker | 2024-10-23 20:21:04.499 | info | "system.adapter.homeconnect.0" enabled
`

**Comment by mcm1957** [comment]
plaese add version info of

js-controller
node

**Comment by Maverick78de** [comment]
node v20.18.0
js-controller 6.0.11

**Comment by TA2k** [comment]
Please test GitHub version

**Comment by Maverick78de** [comment]
GitHub Version reports following errors, but don't crash in loop


homeconnect.0 | 2024-10-24 09:23:53.878 | info | State value to set for "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.active.options.ConsumerProducts_CleaningRobot_Option_TargetAreas" has to be one of type "string", "number", "boolean" but received type "object"
-- | -- | -- | --
homeconnect.0 | 2024-10-24 09:23:53.485 | info | BOSCH-BCR1ACDE-68A40E5666A9/programs/available/ConsumerProducts.CleaningRobot.Program.Cleaning.CleanMap: Program currently not available.
homeconnect.0 | 2024-10-24 09:23:53.179 | info | BOSCH-BCR1ACDE-68A40E5666A9/programs/available/ConsumerProducts.CleaningRobot.Program.Basic.GoHome: Program currently not available.
homeconnect.0 | 2024-10-24 09:23:53.168 | info | BOSCH-BCR1ACDE-68A40E5666A9/programs/available/ConsumerProducts.CleaningRobot.Program.Cleaning.CleanAll: Program currently not available.
homeconnect.0 | 2024-10-24 09:23:52.900 | error | Error: The state contains the forbidden properties x, y!
homeconnect.0 | 2024-10-24 09:23:52.899 | error | Value: '[object Object]'
homeconnect.0 | 2024-10-24 09:23:52.898 | error | failed set state BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo.ConsumerProducts_CleaningRobot_Option_TargetSpot
homeconnect.0 | 2024-10-24 09:23:52.448 | error | Error: The state contains the forbidden properties x, y!
homeconnect.0 | 2024-10-24 09:23:52.447 | error | Value: '[object Object]'
homeconnect.0 | 2024-10-24 09:23:52.446 | error | failed set state BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo.ConsumerProducts_CleaningRobot_Option_TargetSpot
homeconnect.0 | 2024-10-24 09:23:52.432 | info | State value to set for "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.active.options.ConsumerProducts_CleaningRobot_Option_TargetAreas" has to be one of type "string", "number", "boolean" but received type "object"
homeconnect.0 | 2024-10-24 09:23:52.306 | info | No array: selected
homeconnect.0 | 2024-10-24 09:23:52.302 | info | No array: active
homeconnect.0 | 2024-10-24 09:23:46.764 | info | Found 2 devices
homeconnect.0 | 2024-10-24 09:23:46.152 | info | starting. Version 1.4.1 (non-npm: iobroker-community-adapters/ioBroker.homeconnect#777887fd606b9561e180fd4dedad21bbe7dd80bf) in /opt/iobroker/node_modules/iobroker.homeconnect, node: v20.18.0, js-controller: 6.0.11

**Comment by TA2k** [comment]
Please reinstall again

**Comment by Maverick78de** [comment]
reinstalled and now got only some warnings.


homeconnect.0 | 2024-10-24 11:18:53.050 | info | BOSCH-BCR1ACDE-68A40E5666A9/programs/available/ConsumerProducts.CleaningRobot.Program.Cleaning.CleanAll: Program currently not available.
-- | -- | -- | --
homeconnect.0 | 2024-10-24 11:18:52.320 | info | BOSCH-BCR1ACDE-68A40E5666A9/programs/available/ConsumerProducts.CleaningRobot.Program.Cleaning.CleanMap: Program currently not available.
homeconnect.0 | 2024-10-24 11:18:52.137 | info | BOSCH-BCR1ACDE-68A40E5666A9/programs/available/ConsumerProducts.CleaningRobot.Program.Basic.GoHome: Program currently not available.
homeconnect.0 | 2024-10-24 11:18:51.757 | info | State value to set for "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.active.options.BSH_Common_Option_ElapsedProgramTime" has to be type "number" but received type "string"
homeconnect.0 | 2024-10-24 11:18:51.589 | warn | State "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo".ConsumerProducts_CleaningRobot_Option_TargetSpot" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2024-10-24 11:18:51.581 | info | No array: selected
homeconnect.0 | 2024-10-24 11:18:51.579 | info | No array: active
homeconnect.0 | 2024-10-24 11:18:51.516 | warn | State "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo".ConsumerProducts_CleaningRobot_Option_ReferenceMapId" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2024-10-24 11:18:51.486 | warn | Used invalid characters: homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo".ConsumerProducts_CleaningRobot_Option_TargetSpot changed to homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo_.ConsumerProducts_CleaningRobot_Option_TargetSpot
homeconnect.0 | 2024-10-24 11:18:51.478 | warn | Used invalid characters: homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo" changed to homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo_
homeconnect.0 | 2024-10-24 11:18:51.476 | warn | Used invalid characters: homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo".ConsumerProducts_CleaningRobot_Option_ReferenceMapId changed to homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo_.ConsumerProducts_CleaningRobot_Option_ReferenceMapId
homeconnect.0 | 2024-10-24 11:18:51.452 | warn | Used invalid characters: homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo" changed to homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo_
homeconnect.0 | 2024-10-24 11:18:51.429 | warn | State "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo".ConsumerProducts_CleaningRobot_Option_TargetSpot" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2024-10-24 11:18:51.417 | warn | State "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo".ConsumerProducts_CleaningRobot_Option_ReferenceMapId" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2024-10-24 11:18:51.343 | info | State value to set for "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.status.ConsumerProducts_CleaningRobot_Status_Lifted" has to be type "boolean" but received type "string"
homeconnect.0 | 2024-10-24 11:18:51.341 | info | State value to set for "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.status.ConsumerProducts_CleaningRobot_Status_Lost" has to be type "boolean" but received type "string"
homeconnect.0 | 2024-10-24 11:18:51.339 | info | State value to set for "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.status.ConsumerProducts_CleaningRobot_Status_DustBoxInserted" has to be type "boolean" but received type "string"
homeconnect.0 | 2024-10-24 11:18:51.311 | info | State value to set for "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.status.BSH_Common_Status_BatteryLevel" has to be type "number" but received type "string"
homeconnect.0 | 2024-10-24 11:18:51.304 | warn | Used invalid characters: homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo".ConsumerProducts_CleaningRobot_Option_TargetSpot changed to homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo_.ConsumerProducts_CleaningRobot_Option_TargetSpot
homeconnect.0 | 2024-10-24 11:18:51.278 | warn | Used invalid characters: homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo" changed to homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo_
homeconnect.0 | 2024-10-24 11:18:51.276 | warn | Used invalid characters: homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo".ConsumerProducts_CleaningRobot_Option_ReferenceMapId changed to homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo_.ConsumerProducts_CleaningRobot_Option_ReferenceMapId
homeconnect.0 | 2024-10-24 11:18:51.261 | warn | Used invalid characters: homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo" changed to homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.selected.options.GoTo_
homeconnect.0 | 2024-10-24 11:18:51.242 | info | State value to set for "homeconnect.0.BOSCH-BCR1ACDE-68A40E5666A9.programs.active.options.BSH_Common_Option_ElapsedProgramTime" has to be type "number" but received type "string"
homeconnect.0 | 2024-10-24 11:18:49.867 | info | Found 2 devices
homeconnect.0 | 2024-10-24 11:18:49.295 | info | starting. Version 1.4.1 (non-npm: iobroker-community-adapters/ioBroker.homeconnect#08311a0c0ced2a39c20bc5a6ab0dc182ead81700) in /opt/iobroker/node_modules/iobroker.homeconnect, node: v20.18.0, js-controller: 6.0.11
host.iobroker | 2024-10-24 11:18:45.749 | info | instance system.adapter.homeconnect.0 in version "1.4.1" (non-npm: iobroker-community-adapters/ioBroker.homeconnect#08311a0c0ced2a39c20bc5a6ab0dc182ead81700) started with pid 99557

**Comment by TA2k** [comment]
please reinstall again and check if the device is controllable

**Comment by Maverick78de** [comment]
Everything looks good. All devices (dishwasher and robot) are controllable and can't see any errors and warnings anymore.
