### ISSUE TITLE
Backofen wird doppelt angezeigt

### ISSUE THREAD

**Issue by Eistee82** [iobroker-community-adapters/ioBroker.homeconnect#209]
**Describe the bug**  
Der Backofen wird beim starten des Adapter mit der Seriennummer ergänzt durch -001 angelegt. Wenn ich jetzt einen Status ändere z.B. die Tür öffne wird ein weiterer Datenpunkt nur mit der Seriennummer angelegt in dem ich den aktuellen Status sehe. In der Struktur mit -001 wird der falsche status angezeigt bzw dort nicht geändert.

**To Reproduce**  
1. Adapter starten
2. Datenpunkte mit Seriennummer ergänzt durch -001 wird angelegt
3. Status am Gerät ändern
4. Datenpunkt mit Seriennummer wird angelegt und darin ist der aktuelle Status.

**Expected behavior**  
Es sollte nur eine Struktur angelegt werden in der auch der aktuelle Status auch zu sehen ist.

**Screenshots & Logfiles**  
![image](https://github.com/user-attachments/assets/ae6b11a3-add3-40f8-8e02-23232ca9f7cf)

**Versions:**  
 - Adapter version: 1.4.2
 - JS-Controller version: 7.0.3
 - Node version: v20.16.0
 - Operating system: debian

**Comment by TA2k** [comment]
Bitte GitHub version testen

**Comment by Eistee82** [comment]
Die GitHub Version funktioniert wie erwartet

Danke

**Comment by TA2k** [comment]
Auch remote Befehle?

**Comment by Eistee82** [comment]
Nein, remote Befehle funktionieren nicht und Status auch noch nicht richtig. Hab z.B. den Geschirrspüler gestartet und im iobroker steht das er noch aus ist.

**Comment by TA2k** [comment]
wird der status woanders hingeschrieben was sagt der debug log
