### ISSUE TITLE
Info über "Maschinenpflege" verfügbar machen 

### ISSUE THREAD

**Issue by hmersch** [iobroker-community-adapters/ioBroker.homeconnect#22]
Hallo
Ich habe einen Siemens (BSH) Geschirrspüler. Dieser wird vom homeconnect adapter wunderbar erkannt und zeigt die Stati / Programme etc pp an.
Für mich wäre gut, wenn ich auch die Info "Maschinenpflege", die mir im Display angezeigt wird (sieheFoto anbei) im Adapter sehen könnte, denn aktuell vergisst die Familie immer, dass das nötig ist und räumt den GS direkt wieder voll.

Wenn ich helfen kann mit weiteren Infos, unterstütze ich gerne durch Debugging / Testen oder auch beisteuern von irgendwelchen infos. Bitte leitet mich an :-)

Gruss -  

![gs-maschinenpflege](https://user-images.githubusercontent.com/971286/124184778-5af96c80-daba-11eb-9e68-cc902fd64f73.png)

**Comment by TA2k** [comment]
I dont see this in events of the API
https://api-docs.home-connect.com/events?#availability-matrix
Please contact homeconnect to add the event
https://developer.home-connect.com/support/contact

**Comment by hmersch** [comment]
I submitted such a request. Will come back on response

**Comment by ElRedef** [comment]
Hello together,

the Home Connect Android App is able to show such kind of messages.  So it should be already in the API.

Example" Füllstand von Klarspüler niedrig"

**Comment by TA2k** [comment]
The official api is missing a lot of features of the app

**Comment by hmersch** [comment]
Got confirmation that this will be tracked - but currently no plan

**Comment by tschortschde** [comment]
Gibts hierzu was neues?
Diese Funktion würde mich auch interessieren!

**Comment by mcm1957** [comment]
Falls im Api eine diesbezügliche Information hinzugekommen ist bitte neues Issue öffnen und einen Link zur entsprechenden Doku angeben.

**Comment by tschortschde** [comment]
Ok. Leider habe ich dazu nichts gefunden. 
versuche mal den Entwickler der API zu erreichen....

**Comment by hmersch** [comment]
Es hilft sicherlich mehrere Anfragen dort zu plazieren, ja - bitte anmailen

**Comment by ElRedef** [comment]
Hallo,

zumindest was meine Anfrage oben anbelangt ist das Problem gelöst. _Klarspühler leer_ und _Salz leer_ gibt es inzwischen in den Events.

**Comment by tschortschde** [comment]
Danke für die Infos
@ElRedef
In welchem Objekt wird dir das angezeigt?

**Comment by ElRedef** [comment]
'homeconnect.0.01101051XXXXXXXXXX.events.Dishcare_Dishwasher_Event_SaltNearlyEmpty''
