### ISSUE TITLE
Which status do I need to set/change to start a dishwasher remotely?

### ISSUE THREAD

**Issue by ThoSt81** [iobroker-community-adapters/ioBroker.homeconnect#24]
The device is in remote start and showing true for

homeconnect.0.SIEMENS-XXX.status.BSH_Common_Status_RemoteControlActive
homeconnect.0.SIEMENS-XXX.status.BSH_Common_Status_RemoteControlStartAllowed

Not sure what to do to finally start the program?

**Comment by heikowe** [comment]
same problem here. I am not able to start the dishwasher and run a program. Connection works.
An example which field to update would be nice

**Comment by noriyuki41** [comment]
Same problem with my device. Tried to optimize remote start with the electricity price but noting could start the dishwasher. Please

**Comment by trollvottel** [comment]
Same. The adapter is kinda useless without this functionality.

**Comment by TA2k** [comment]
https://github.com/iobroker-community-adapters/ioBroker.homeconnect#benutzung

**Comment by trollvottel** [comment]
Yeah, saw that. But how to remotely start the program that got preselected locally on the appliance?

**Comment by trollvottel** [comment]
Ah! Stupid me! Need to check for selected program and then set that as active?

**Comment by heikowe** [comment]
this works for me: 

`setState("homeconnect.xxx.settings.BSH_Common_Setting_PowerState"/*Energiezustand*/, 'BSH.Common.EnumType.PowerState.On');
      setStateDelayed("homeconnect.xxx.programs.active.BSH_Common_Root_ActiveProgram"/*BSH_Common_Root_ActiveProgram*/, 'Dishcare.Dishwasher.Program.Auto2', 25000, true);`
