### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by vr6syncro** [iobroker-community-adapters/ioBroker.homeconnect#25]
ioBroker ist up to date. Adapter auch.
Node 12 NPM 6

`
<html>
<body>

omeconnect.0 | 2021-08-09 11:45:31.917 | error | {"data":{"programs":[]}}
-- | -- | -- | --
homeconnect.0 | 2021-08-09 11:45:31.916 | error | /programs
homeconnect.0 | 2021-08-09 11:45:31.916 | error | TypeError: Cannot read property 'forEach' of undefined at /opt/iobroker/node_modules/iobroker.homeconnect/main.js:1041:57 at Array.forEach (<anonymous>) at /opt/iobroker/node_modules/iobroker.homeconnect/main.js:1032:39 at processTicksAndRejections (internal/process/task_queues.js:97:5)
homeconnect.0 | 2021-08-09 11:45:31.911 | error | TypeError: Cannot read property 'forEach' of undefined

</body>
</html>`

Ich habe 3 Geräte und seit neuestem eine Dunstabzugshaube. Ich bin der Meinung das es seit dem ist.
DWK98PR60

**Comment by TA2k** [comment]
Ja die Dunstabzugshaube hat keine programme. Ist auf github schon gefixt aber noch nicht released. Fehler ist aber nicht kritisch

**Comment by vr6syncro** [comment]
https://github.com/iobroker-community-adapters/ioBroker.homeconnect/issues/25#issuecomment-895097839
