### ISSUE TITLE
Too many requests. Adapter sends too many requests per minute

### ISSUE THREAD

**Issue by Scotty-89** [iobroker-community-adapters/ioBroker.homeconnect#26]
Hey,

ich bekomme jetzt seit kurzen Felelrmeldungen:

![image](https://user-images.githubusercontent.com/54929714/130781857-38f53f2d-51ab-47a2-be50-25f88229ac63.png)

mein System nutzt den aktuellen SW Stände...

**Comment by Zaschii** [comment]
same here

**Comment by astrakid** [comment]
i get a message that i have to wait x hours. only 1000 requests are allowed per day.
1000/24 hours => ca 40 requests per hour

could a rate limiter be setup (either configurable or at least static) to send a request every x minutes (every 2 minute if static)?

kind regards,
andre

**Comment by CarstenP51** [comment]
Hallo,

ich benutze den Adapter in der Vers. 1.0.1 und ich bekomme jeden Tag diese Fehlermeldung

![94e0525272468b1f35019ab60cae40b5](https://user-images.githubusercontent.com/107586480/173933935-d3c6b48a-9b66-4788-8e5a-fa4095fdc4e8.png)

Viele Grüße

**Comment by TA2k** [comment]
Wieviele und welche Geräte hast du angeschlossen

**Comment by CarstenP51** [comment]
2 Geräte sind angeschlossen, 1 Backofen und 1 Geschirrspüler.
Der Backofen ist ca. 8 Jahre alt, der Geschirrspüler 1 Jahr


![126d665d264375dfd125518fa4760a35](https://user-images.githubusercontent.com/107586480/173998437-8e8aa5eb-11e2-45a0-9c7e-90d5455b1a22.png)
.

**Comment by TA2k** [comment]
Bräuchte ich ein log im log level debug
tombox2020@gmail.com
