### ISSUE TITLE
Verschiedene Statusmeldungen funktionieren nicht

### ISSUE THREAD

**Issue by tigerjoerg** [iobroker-community-adapters/ioBroker.homeconnect#31]
Hallo zusammen,
verschiedene Statusmeldungen funktionieren nicht:

homeconnect.0.SIEMENS-WT47XM40-XXXXXXXXXX.programs.selected.options.Mix.LaundryCare_Dryer_Option_Gentle
homeconnect.0.SIEMENS-WT47XM40-XXXXXXXXXX.programs.selected.options.Mix.LaundryCare_Dryer_Option_DryingTargetAdjustment
homeconnect.0.SIEMENS-WT47XM40-XXXXXXXXXX.programs.selected.options.Mix.LaundryCare_Dryer_Option_DryingTargetAdjustment
[...]

Ich kann hier einstellen was ich möchte und es passiert an der Maschine nichts. Wenn ich am Trockner was ändere, passiert auch in den Werten nichts.

Folgende Fehlermeldung erhalte ich bei den Werten, wenn ich was ändere:
Put folder failed SIEMENS-WT47XM40-XXXXXXXXXX/commands/LaundryCare.Dryer.Option.Gentle{"data":{"key":"LaundryCare.Dryer.Option.Gentle","value":true}}

Kann man die Zeit des Updates von der Restzeit verkürzen?

Vielen Dank fürs kümmern. Ansonsten super Adapter!

Viele Grüße

Jörg

**Comment by TA2k** [comment]
Es scheint so als würde die api diese options nicht unterstützen 
anscheinend ist nur eine option erlaubt
https://api-docs.home-connect.com/programs-and-options?#dryer_drying-target-option
