### ISSUE TITLE
Refresh token fails

### ISSUE THREAD

**Issue by trollvottel** [iobroker-community-adapters/ioBroker.homeconnect#32]
The adapter stopped working for me, see log below. Interesting to note: It says it'll retry in 5m, but next log entry is only three seconds later?!? This probably triggers rate-limit!

homeconnect.0 | 2022-02-06 22:31:23.517 | warn | Retry Refresh Token in 5min
homeconnect.0 | 2022-02-06 22:31:23.517 | error | Error Refresh-Token: 429 undefined
homeconnect.0 | 2022-02-06 22:31:20.371 | warn | Retry Refresh Token in 5min
homeconnect.0 | 2022-02-06 22:31:20.370 | error | Error Refresh-Token: 429 undefined
homeconnect.0 | 2022-02-06 22:31:17.977 | warn | Retry Refresh Token in 5min
homeconnect.0 | 2022-02-06 22:31:17.977 | error | Error Refresh-Token: 429 undefined
homeconnect.0 | 2022-02-06 22:31:17.663 | warn | Retry Refresh Token in 5min
homeconnect.0 | 2022-02-06 22:31:17.663 | error | Error Refresh-Token: 429 undefined
homeconnect.0 | 2022-02-06 22:31:15.380 | warn | Retry Refresh Token in 5min
homeconnect.0 | 2022-02-06 22:31:15.379 | error | Error Refresh-Token: 429 undefined

**Comment by trollvottel** [comment]
Adapter restart seems to at least "heal" the 5m retry timespan:

homeconnect.0 | 2022-02-06 22:36:30.031 | warn | Retry Refresh Token in 5min
homeconnect.0 | 2022-02-06 22:36:30.031 | error | Error Refresh-Token: 429 undefined
homeconnect.0 | 2022-02-06 22:31:37.914 | info | BOSCH-SBV68TX06E-XXXXXXX: There is no program active
homeconnect.0 | 2022-02-06 22:31:34.542 | info | BOSCH-SBV68TX06E-XXXXXXX: There is no program active
homeconnect.0 | 2022-02-06 22:31:29.932 | warn | Retry Refresh Token in 5min
homeconnect.0 | 2022-02-06 22:31:29.931 | error | Error Refresh-Token: 429 undefined
homeconnect.0 | 2022-02-06 22:31:29.701 | info | starting. Version 0.0.37 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v14.18.2, js-controller: 3.3.22
homeconnect.0 | 2022-02-06 22:31:29.692 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
homeconnect.0 | 2022-02-06 22:31:25.831 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
homeconnect.0 | 2022-02-06 22:31:25.830 | info | terminating
homeconnect.0 | 2022-02-06 22:31:25.828 | info | cleaned everything up...
homeconnect.0 | 2022-02-06 22:31:25.828 | info | Got terminate signal TERMINATE_YOURSELF

**Comment by Aprilia1982** [comment]
Had the same issue yesterday. Now it work probably again. Maybe create a new app token and restart auth process as documented.

**Comment by trollvottel** [comment]
If I hadn't done that already just a few days ago, I'd have said nothing..

**Comment by TA2k** [comment]
fixed with 1.0.0
