### ISSUE TITLE
Events erst nach dem ersten Auftreten angelegt

### ISSUE THREAD

**Issue by neopholus** [iobroker-community-adapters/ioBroker.homeconnect#33]
Hallo,

toller Adapter, vielen Dank!

Da ich immer Fehler hatte wegen zu kleinen/großen Werten, bin ich der Empfehlung hier in einigen der Issues gefolgt und habe die Objekte alle gelöscht. Beim Neustart des Adapters wurden sie wieder angelegt, die Fehler sind weg. Soweit, so gut.

Nun ist mir aufgefallen, dass die Events nicht angelegt werden, z.B.
homeconnect.0.SIEMENS-KG49XXXXX-XXXXXXXXXXXX.events.Refrigeration_FridgeFreezer_Event_DoorAlarmRefrigerator
Habe jetzt mal die Tür etwas offen stehen lassen, bis der Kühlschrnk piepte, dann wurde das Event angelegt.

Laut [https://api-docs.home-connect.com/events#availability-matrix](https://api-docs.home-connect.com/events#availability-matrix) müsste es insgesammt drei Events geben:
- Refrigeration.FridgeFreezer.Event.DoorAlarmFreezer  
- Refrigeration.FridgeFreezer.Event.DoorAlarmRefrigerator  
- Refrigeration.FridgeFreezer.Event.TemperatureAlarmFreezer  

Ich würde jetzt ungern das Gefrierfach so lange offen stehen lassen, bis der Temperatur-Alarm ausgelöst wird, so dass das Event in ioBroker angelegt wurd. Ich würde das Event aber gerne am Handy gemeldet bekommen, kann aber natürlich keine on-Subscription auf das Event anlegen, solange der Datenpunkt nicht da ist.

Wie können die fehlenden Events angelegt werden?

Danke,
Stefan

**Comment by TA2k** [comment]
Man könnte auch die raw beschreibung des states unter Objekte bearbeiten

**Comment by neopholus** [comment]
Hallo TA2k, 

du meinst, manuell im Objects-Baum hinzufügen und dann editieren?
Dann versuche ich das mal...

Danke,
Stefan

**Comment by neopholus** [comment]
Hallo TA2k,

klappt leider nicht. Selbst im Expertenmodus kann ich unter "events" keinen Datenpunkt anlegen, nur ein Verzeichnis.
Das scheint ein Bug in ioBroker zu sein. 

Mit Javascript createState werden die Datenpunkte auch nicht angelegt, ich denke, createState legt nur unter 0_userdata Datenpunkte an.

Viele Grüße
Stefan
