### ISSUE TITLE
Aktualisierung der Daten erst nach manuellem Neustart des Adapters

### ISSUE THREAD

**Issue by JVF2** [iobroker-community-adapters/ioBroker.homeconnect#34]
Der Adapter zeigt "Verbunden mit Host" und "Lebenszeichen" mit einem grünen Haken an, dennoch werden die Werte nicht aktualisiert.
Nach einem Neustart des Adapters funktioniert alles einwandfrei.
Leider muss ich den Vorgang regelmäßig wiederholen.
Der "Log" weist diesbezüglich keine Einträge auf.

Hat jemand eine Idee?

Besten Dank vorab.

**Comment by tigerjoerg** [comment]
Ich habe das gleiche Problem. Der Wäschetrockner läuft, aber es kommen keine Statusmeldungen über den Adapter.
Erst nach einem Neustart funktioniert wieder alles.
Lebenszeichen etc. alles vorhanden. Keine Meldung im "normalen" Logfile
Seit ca. 2-3 Wochen habe ich das Problem.

**Comment by obodeldog** [comment]
Same here

**Comment by TA2k** [comment]
Problem durch BSH API behoben
