### ISSUE TITLE
Werte updaten funktioniert nicht mehr

### ISSUE THREAD

**Issue by heikowe** [iobroker-community-adapters/ioBroker.homeconnect#35]
Leider funktioniert das Updaten eines beliebigen Wertes bei mir nicht mehr (Spülmaschine).
Beispiel: 
`Put settings failed ***/commands/BSH.Common.Setting.PowerState{"data":{"key":"BSH.Common.Setting.PowerState","value":"BSH.Common.EnumType.PowerState.On","type":"BSH.Common.Setting.PowerState"}}`

Auch das neustarten der Instanz / neu erstellen hat nichts gebracht.

V 0.0.37

**Comment by TA2k** [comment]
Kannst du bitte mehr log information bereitstellen

**Comment by heikowe** [comment]
`
homeconnect.0 | 2022-02-21 13:24:01.563 | error | EventSource error: {"type":"error"}
-- | -- | -- | --
homeconnect.0 | 2022-02-21 13:23:14.653 | error | Put settings failed ***/commands/BSH.Common.Setting.PowerState{"data":{"key":"BSH.Common.Setting.PowerState","value":"BSH.Common.EnumType.PowerState.On","type":"BSH.Common.Setting.PowerState"}}
homeconnect.0 | 2022-02-21 13:23:14.653 | info | 409: HomeAppliance did not respond in time.
homeconnect.0 | 2022-02-21 13:23:02.636 | info | Undefined Error from Homeconnect this happens sometimes.

`

**Comment by TA2k** [comment]
Anscheind is der Geschirrspüler nicht erreichbar. Geht denn alles über die App?

**Comment by TA2k** [comment]
Die API sagt leider er kann das gerät nicht erreichen

**Comment by TA2k** [comment]
Problem wurde von BSH API behoben
