### ISSUE TITLE
"forEach" undefined and other errors

### ISSUE THREAD

**Issue by BlueSnake830** [iobroker-community-adapters/ioBroker.homeconnect#4]
There are several errors in the ioBroker log:

 | error | (26901) {"data":{"programs":[]}}
 | error | (26901) /programs
 error | (26901) TypeError: Cannot read property 'forEach' of undefined     at /opt/iobroker/node_modules/iobroker.homeconnect/main.js:943:57     at Array.forEach (<anonymous>)     at /opt/iobroker/node_module
 | error | (26901) TypeError: Cannot read property 'forEach' of undefined

**Comment by TA2k** [comment]
Did you really install the latest version? Try to reinstall via github please

**Comment by BlueSnake830** [comment]
I installed 0.0.31, since this was the last version which is provided in ioBroker. Also I observe many of these logs:


homeconnect.0 | 2021-01-13 11:15:00.946 | error | (20746) 429 Too Many Requests
-- | -- | -- | --
homeconnect.0 | 2021-01-13 11:15:00.944 | error | (20746) EventSource error: {"type":"error","status":429,"message":"Too Many Requests"}
