### ISSUE TITLE
State nicht vorhanden #2

### ISSUE THREAD

**Issue by holofury** [iobroker-community-adapters/ioBroker.homeconnect#40]
Issue #37 wurde leider nicht behoben, es taucht noch immer die Meldung auf:

homeconnect.0 (1829) State "homeconnect.0.710060514461009163.programs.active.options.BSH_Common_Option_RemainingProgramTime" has no existing object, this might lead to an error in future versions

Da auf das alte Issue keine Reaktion mehr kam, jetzt ein neues Issue diesbezüglich.

**Comment by TA2k** [comment]
Bitte die aktuelle github version testen

**Comment by holofury** [comment]
Hab ich schon versucht.
Hat sich auch nur über npm install installieren lassen.
Leider kein Erfolg, Versionsnummer bleibt auch bei 1.0.1 stehen.

**Comment by TA2k** [comment]
habe am 07.06. 23:00 Uhr Änderung gemacht bitte nochmal via github installieren

**Comment by zaphod2** [comment]
jetzt verbindet sich der Dienst nicht mehr

**Comment by holofury** [comment]
Fehler ist immer noch vorhanden:

homeconnect.0 | 2022-06-12 11:33:16.207 | warn | State "homeconnect.0.SIEMENS-TI9575X9FU-68A40E551939.programs.active.options.BSH_Common_Option_RemainingProgramTime" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2022-06-12 11:31:00.534 | warn | State "homeconnect.0.SIEMENS-TI9575X9FU-68A40E551939.programs.active.options.BSH_Common_Option_RemainingProgramTime" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2022-06-12 11:27:48.165 | warn | State "homeconnect.0.SIEMENS-TI9575X9FU-68A40E551939.programs.active.options.BSH_Common_Option_RemainingProgramTime" has no existing object, this might lead to an error in future versions

**Comment by zaphod2** [comment]
Bei mir sind Fehler behoben.

**Comment by holofury** [comment]
Bei mir nicht, Fehler ist noch da:

homeconnect.0 | 2022-06-17 17:21:09.614 | warn | State "homeconnect.0.710060514461009163.programs.active.options.BSH_Common_Option_RemainingProgramTime" has no existing object, this might lead to an error in future versions

**Comment by holofury** [comment]
Fehler ist immer noch aktuell:

homeconnect.0 | 2022-07-28 20:10:41.590 | warn | State "homeconnect.0.710060514461009163.programs.active.options.BSH_Common_Option_RemainingProgramTime" has no existing object, this might lead to an error in future versions

**Comment by holofury** [comment]
Einmal im Monat schreib ich hier was rein.
Mal schauen, ob das überhaupt gelesen wird?!

**Comment by TA2k** [comment]
Sollte mit der GitHub version nicht auftreten wenn doch wäre gut zu wissen wann es auftritt

**Comment by holofury** [comment]
Die Github Version Ist schon installiert.
Die Meldung kommt logischerweise, wenn ein Programm aktive ist.
Der Fehler taucht sowohl bei der Kaffeemaschine EQ.9 als auch beim CookIt auf.

**Comment by TA2k** [comment]
Wenn das Programm beendet wird oder gestartet

**Comment by holofury** [comment]
Wenn das Programm gestartet wird.

**Comment by zaphod2** [comment]
Verzeichnisbaum und dann Adapter gelöscht und die github version neu installiert?
Bei mir gehts ja seid dem problemlos wieder.

**Comment by holofury** [comment]
Hab die Schritte jetzt nochmal durchgeführt.
Ich melde mich, ob die Meldungen jetzt weg sind.

**Comment by holofury** [comment]
Jetzt wollte ich hier gerade schließen, weil ich die Meldungen nicht mehr im Log hatte, da tauchten sie wieder auf:

homeconnect.0 | 2022-08-24 08:36:19.665 | warn | State "homeconnect.0.SIEMENS-TI9575X9FU-68A40E551939.programs.active.options.BSH_Common_Option_RemainingProgramTime" has no existing object, this might lead to an error in future versions

:-(

**Comment by TA2k** [comment]
Kannst du das in Beziehung ob das gerät ausgeschaltet oder eingeschaltet wurde oder das Programm geändert wurde

**Comment by holofury** [comment]
Ich habs gerade nochmal getestet.
Die Meldung kommt nach Programmende, nicht beim Start. Das stimmte bei meinem letzten Post also nicht.

Hier die kompletten Meldungen beim Bezug eines Kaffees:

homeconnect.0
2022-08-24 13:32:31.811	info	SIEMENS-TI9575X9FU-68A40E551939/programs/selected/options: There is no program selected.

homeconnect.0
2022-08-24 13:29:40.003	info	SIEMENS-TI9575X9FU-68A40E551939/programs/active/options: There is no program active.

homeconnect.0
2022-08-24 13:29:38.720	warn	State "homeconnect.0.SIEMENS-TI9575X9FU-68A40E551939.programs.active.options.BSH_Common_Option_RemainingProgramTime" has no existing object, this might lead to an error in future versions

homeconnect.0
2022-08-24 13:27:32.386	info	SIEMENS-TI9575X9FU-68A40E551939/programs/selected/options: There is no program selected.

homeconnect.0
2022-08-24 13:26:44.211	info	SIEMENS-TI9575X9FU-68A40E551939/programs/active/options: There is no program active.

**Comment by TA2k** [comment]
Ich habe noch ein paar checks eingebaut bitte nochmal die GitHub version testen

**Comment by holofury** [comment]
Moin,
hat etwas gedauert, weil ich im Urlaub war.
Jetzt sind die ersten Kaffees aber getrunken und bislang kam keine Fehlermeldung mehr.
Ich mach dann mal zu.

Danke fürs Beheben! :-)
