### ISSUE TITLE
Adapter verbindet sich nicht mit Home Connect

### ISSUE THREAD

**Issue by XeQutR** [iobroker-community-adapters/ioBroker.homeconnect#43]
**Describe the bug**  
Adapter lässt sich nicht erfolgreich mit HomeConnect verbinden. Alle Schritte wurden laut Anleitung durchgeführt.
ioBroker Log zeigt folgende Fehlermeldung an:

_"please enter homeconnect app username and password and clientId in the instance settings"_

**To Reproduce**  
1. Installation des homeconnect Adapters
2. Im Home Connect DEV Portal eine neue Application registrieren mit dem Namen "iobroker" und "OAuth Flow" auf "Device Flow" setzen.
4.  Home Connect ClientID im Konfigurationsfenster der Adapterinstanz eintragen und speichern.
5. Instanz zeigt nur die Stati "Connected to host" und "Heartbeat" grün an. Status "Connected to device or service" ist rot
6. ioBroker Log zeigt nur eine Warnung an (siehe Description)7. 
7. Es werden keine Objekte (Geräte) von Home Connect erstellt / importiert.

**Expected behavior**  
Adapter verbindet sich erfolgreich mit Home Connect und importiert alle Gerätedaten unter ioBroker Objekte.

**Screenshots & Logfiles**  
Kann gerne auf Nachfrage bereitgestellt werden.

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: 4.0.23
 - Node version: 14.19.3 
 - Operating system: Debian 4.19.152-1

**Additional context**  
N/A

**Comment by TA2k** [comment]
Anscheinend hast du  in den optionen nicht alle felder ausgefüllt

**Comment by XeQutR** [comment]
Hallo TA2K,

von welchen Optionen sprichst du? Auf der Adapterseite oder Home Connect?

**Comment by XeQutR** [comment]
Das habe ich bereits gemacht. Bekomme immer noch folgende Fehlermeldung.

![Screenshot 2022-06-23 at 20 51 39](https://user-images.githubusercontent.com/108079564/175375582-76b11aa9-8fed-4c6f-a8d3-def368c9a3c1.png)

Wenn ich in HomeConnect DEV Portal nachschauen, dann habe ich im DEV Account den Default (Test) Account mit Mailadresse von meiner Home Connect App angegeben. Sollte doch so passen, oder?

Wenn ich jedoch die URL aus dem Log nehme und mich versuche mit dem Account von der Home Connect App anzumelden, bekomme ich eine weitere Fehlermeldung.

![Screenshot 2022-06-23 at 20 53 38](https://user-images.githubusercontent.com/108079564/175376143-cfa6eae9-fce5-4a0a-9bbf-99659f545e1a.png)

Sieht nach irgendwelche Berechtigungsproblemen aus. Komme irgendwie nicht weiter.
Irgendeine Idee was ich falsch mache?

**Comment by XeQutR** [comment]
Das habe ich auch überprüft. Da bekanntlich im Passwort auch Sonderzeichen sein müssen, gehe ich davon aus, dass der Adapter bei der Übertragen an die API damit klar kommt, oder? Nicht dass das Sonderzeichen vielleicht zu Problemen führt.

**Comment by XeQutR** [comment]
Hab das Problem gefunden!
Man muss die Home Connect App Mailadresse im Adapter nehmen und nicht die vom DEV Account.

Danke dennoch TA2k für deine Unterstützung!

**Comment by Domi920** [comment]
Habe auch Probleme, eine Verbindung herzustellen.

@XeQutR & @TA2k  hoffe Ihr könnte mir dabei helfen:
https://github.com/iobroker-community-adapters/ioBroker.homeconnect/issues/48

Danke im Voraus!

Gruß Dominik
