### ISSUE TITLE
Adapter verbindet sich nicht mit Home Connect

### ISSUE THREAD

**Issue by Domi920** [iobroker-community-adapters/ioBroker.homeconnect#48]
Hallo, 
habe bereits schon einen ähnlichen Beitrag gefunden.:
https://github.com/iobroker-community-adapters/ioBroker.homeconnect/issues/43
Leider funktioniert es trotzdem nicht.

Ich habe 2 verschiedene Accounts:
- einen über den die HomeConnect Geräte verbunden sind (pia.b ....)
- einen fürs Entwicklerkonto (dominik.b...)

folgende Einstellungen habe ich getätigt:
![2022-09-28 (1)](https://user-images.githubusercontent.com/68474558/192746871-df7a54db-3b88-4cf4-8e50-41318fa3345c.png)
![2022-09-28 (2)](https://user-images.githubusercontent.com/68474558/192746897-6fea0ab0-11e0-42cc-916c-562533affcec.png)
![2022-09-28 (3)](https://user-images.githubusercontent.com/68474558/192747011-b9282275-d392-4518-9c8f-ca1149761edd.png)
![2022-09-28 (4)](https://user-images.githubusercontent.com/68474558/192747024-ed0357e1-ca43-43eb-bc78-8f9e5b646dcc.png)
![2022-09-28 (5)](https://user-images.githubusercontent.com/68474558/192747047-a20dc40b-9885-4932-87c2-d2f2da6c8d26.png)

Erhalte folgende Meldungen im Protokoll:
![2022-09-28 (6)](https://user-images.githubusercontent.com/68474558/192747151-6f66b015-a071-419f-83cf-6302382c23bf.png)

Wenn ich en Link aufrufe und mich anmelde komme ich auf diese Seite:
![2022-09-28 (7)](https://user-images.githubusercontent.com/68474558/192747212-d01db395-8eba-48ab-88d6-96560b25821c.png)

Nachdem ich bestätigt habe, werde ich auf diese Seite weitergeleitet (Die Seite die ich vorher bei Success Redirect angegeben habe):
![2022-09-28 (8)](https://user-images.githubusercontent.com/68474558/192747404-325e5a21-8d11-419c-98d5-86a62137b83f.png)

Nach einen Neustart des Adapters kommt die wieder die "gleiche" Fehlermeldung:
![2022-09-28 (9)](https://user-images.githubusercontent.com/68474558/192747532-fb76be46-eaa6-4f78-a209-a5a0d998d293.png)

Der Status bleibt leider unverändert:
![2022-09-28 (10)](https://user-images.githubusercontent.com/68474558/192747760-49df8256-73c8-49a4-9c49-77319eff1dca.png)

Das Passwort ist beim Entwickler-Konto & beim HomeConnect-Konto das gleiche.
Es beinhaltet allerdings Sonderzeichen.

Habe schon verschiedene Einstellungen durchprobiert, aber alles erfolglos.

Was mache ich falsch?

Meine System Infos:
Node.js v16.17.0 
NPM 8.15.0

Gruß Dominik

**Comment by TA2k** [comment]
kannst du dich mit pia.b  bei dem link im log mit dem code am ende einloggen?

**Comment by Domi920** [comment]
Ja, ich kann mich einloggen.
Direkt danach erscheint:
![2022-09-28 (7)](https://user-images.githubusercontent.com/68474558/192763589-a58ea2c2-cb48-4772-981f-34afe1d72396.png)

Nachdem ich Approve geklickt habe sehe ich die Success Redirect URL:
![2022-09-28 (8)](https://user-images.githubusercontent.com/68474558/192763717-cdbb3e26-b7d0-4a5e-bd39-a52ba1b9adbc.png)


Dann gehts wieder weiter mit dem LOG, in Dauerschleife, solange man es versucht :-(

**Comment by TA2k** [comment]
![](https://github.com/iobroker-community-adapters/ioBroker.homeconnect/blob/master/img/application2.JPG)

**Comment by Domi920** [comment]
Dann bekomme ich das im LOG

`Error:
homeconnect.0 (3982) Error: Request failed with status code 400
homeconnect.0 (3982) {"error":"unauthorized_client","error_description":"request rejected by client authorization authority (developer portal)"}
homeconnect.0 (3982) No verification_uri_complete in device_authorization`

**Comment by Domi920** [comment]
Wenn ich den Adapter wieder neustarte kommt plötzlich wieder die Meldung:
`<html>
<body>


homeconnect.0 | 2022-09-28 13:30:43.293 | error | {"error":"authorization_pending","error_description":"The authorization request is still pending as the end-user hasn't yet completed the user interaction steps"}
-- | -- | -- | --
homeconnect.0 | 2022-09-28 13:30:43.292 | error | Error: Request failed with status code 400
homeconnect.0 | 2022-09-28 13:30:43.291 | error | Please check username and password check manually here: https://api.home-connect.com/security/oauth/device_verify?user_code=NM75-MM3A


</body>
</html>`

Sehr seltsam....

**Comment by kleinjn** [comment]
Ich habe genau das gleiche Problem und auch schon die gleichen Schritte versucht, lande auch immer wieder bei der gleichen Meldung im Log

**Comment by TA2k** [comment]
Bitte mal den debug log aktivieren und mir via mail schicken
tombox2020@gmail.com

**Comment by Domi920** [comment]
@TA2k habe dir das Log gesendet. Ist es angekommen?

**Comment by TA2k** [comment]
Nutzt ihr diese SingleKey Sache?

**Comment by TA2k** [comment]
Bitte die GitHub version installieren da kann man sich manuell einloggen

**Comment by Domi920** [comment]
@TA2k Es funktioniert!!!
Nach den manuellen einloggen durch den Link hat es sofort geklappt.
Vielen vielen Dank!!!

Die Datenpunkte sind alle vorhanden und so wie es aussieht werden die Daten aktualisiert.
Kann es heute Nachmittag besser überprüfen.

Ja ich nutze SingleKey, das wurde automatisch angeboten, da gabs keine Auswahl.

**Comment by TA2k** [comment]
SingleKey kannte ich bisher nicht verwendest du das auch für die Homeconnect App?

**Comment by Domi920** [comment]
Klar, von der Homeconnect App wurde ich sofort an SingleKey weitergeleitet.
Sieht so aus als würde kein Weg dran vorbei führen.

**Comment by kleinjn** [comment]
Jetzt klappt es mit der Anmeldung, der Adapter wird grün, nur habe ich jetzt ein 'expired token'. Setze ich den Haken im Adapter zum Erneuern des Token, dann habe ich wieder das Problem mit der Anmeldung....

2022-09-29 11:41:10.236  - error: homeconnect.0 (407628) Please check username and password or visit this site for manually login:
--
2022-09-29 11:41:10.237  - error: homeconnect.0 (407628) Bitte überprüfe Benutzername und Passwort oder besuche diese Seite für manuelle Anmeldung:
2022-09-29 11:41:10.238  - error: homeconnect.0 (407628) https://api.home-connect.com/security/oauth/device_verify?user_code=DQKF-DDRB
2022-09-29 11:41:10.238  - error:  homeconnect.0 (407628)  {"error":"expired_token","error_description":"Device authorization  session not found, expired or blocked"}
2022-09-29 11:41:10.239  - info: homeconnect.0 (407628) Wait 10 seconds to retry

**Comment by kleinjn** [comment]
So funktionniert auch bei mir jetzt! Vielen, vielen Dank....

**Comment by Heartblood76** [comment]
Nachdem ich quasi gezwungen wurde auf SingelKey umzusteigen stehe ich jetzt vor dem selben Problem, der Adapter kann sich nicht verbinden.
Den Tipp mit der Version von GitHub habe ich versucht, ich finde aber keinen manuellen Login.

**Comment by TA2k** [comment]
mit v1.1.0 sollte es keine Probleme beim login geben. wenn doch braucht man ein genauen Fehler

**Comment by Heartblood76** [comment]
<html>
<body>


homeconnect.0 | 2022-11-02 14:08:43.166 | info | Token abgelaufen
-- | -- | -- | --
homeconnect.0 | 2022-11-02 14:08:43.166 | error | Start Event Stream Error: {"type":"error","status":401,"message":"Unauthorized"}
homeconnect.0 | 2022-11-02 14:08:43.165 | error | 401 Unauthorized
homeconnect.0 | 2022-11-02 14:08:38.031 | info | Keep Alive failed Reconnect EventStream
homeconnect.0 | 2022-11-02 14:07:33.203 | info | Token abgelaufen
homeconnect.0 | 2022-11-02 14:07:33.203 | error | Start Event Stream Error: {"type":"error","status":401,"message":"Unauthorized"}
homeconnect.0 | 2022-11-02 14:07:33.202 | error | 401 Unauthorized
homeconnect.0 | 2022-11-02 14:07:28.028 | info | Keep Alive failed Reconnect EventStream
homeconnect.0 | 2022-11-02 14:06:23.154 | info | Token abgelaufen
homeconnect.0 | 2022-11-02 14:06:23.153 | error | Start Event Stream Error: {"type":"error","status":401,"message":"Unauthorized"}
homeconnect.0 | 2022-11-02 14:06:23.153 | error | 401 Unauthorized
homeconnect.0 | 2022-11-02 14:06:18.024 | info | Keep Alive failed Reconnect EventStream
homeconnect.0 | 2022-11-02 14:05:13.158 | info | Token abgelaufen
homeconnect.0 | 2022-11-02 14:05:13.158 | error | Start Event Stream Error: {"type":"error","status":401,"message":"Unauthorized"}
homeconnect.0 | 2022-11-02 14:05:13.157 | error | 401 Unauthorized
homeconnect.0 | 2022-11-02 14:05:08.020 | error | {"error":{"key":"SDK.Error.504.GatewayTimeout","description":"Timeout on Home Connect subsystem. Please try it again."}}
homeconnect.0 | 2022-11-02 14:05:08.020 | error | AxiosError: Request failed with status code 504
homeconnect.0 | 2022-11-02 14:05:01.350 | info | Token received succesfully
homeconnect.0 | 2022-11-02 14:04:51.192 | info | Wait 10 seconds to retry
homeconnect.0 | 2022-11-02 14:04:51.192 | error | {"error":"authorization_pending","error_description":"The authorization request is still pending as the end-user hasn't yet completed the user interaction steps"}
homeconnect.0 | 2022-11-02 14:04:51.192 | error | https://api.home-connect.com/security/oauth/device_verify?user_code=XPXI-F94U
homeconnect.0 | 2022-11-02 14:04:51.191 | error | Bitte überprüfe Benutzername und Passwort oder besuche diese Seite für manuelle Anmeldung:
homeconnect.0 | 2022-11-02 14:04:51.191 | error | Please check username and password or visit this site for manually login:
homeconnect.0 | 2022-11-02 14:04:51.191 | error | AxiosError: Request failed with status code 400
homeconnect.0 | 2022-11-02 14:04:41.071 | info | Wait 10 seconds to retry
homeconnect.0 | 2022-11-02 14:04:41.071 | error | {"error":"authorization_pending","error_description":"The authorization request is still pending as the end-user hasn't yet completed the user interaction steps"}
homeconnect.0 | 2022-11-02 14:04:41.071 | error | https://api.home-connect.com/security/oauth/device_verify?user_code=XPXI-F94U
homeconnect.0 | 2022-11-02 14:04:41.071 | error | Bitte überprüfe Benutzername und Passwort oder besuche diese Seite für manuelle Anmeldung:
homeconnect.0 | 2022-11-02 14:04:41.071 | error | Please check username and password or visit this site for manually login:
homeconnect.0 | 2022-11-02 14:04:41.070 | error | AxiosError: Request failed with status code 400
homeconnect.0 | 2022-11-02 14:04:30.958 | info | Wait 10 seconds to retry
homeconnect.0 | 2022-11-02 14:04:30.958 | error | {"error":"authorization_pending","error_description":"The authorization request is still pending as the end-user hasn't yet completed the user interaction steps"}
homeconnect.0 | 2022-11-02 14:04:30.958 | error | https://api.home-connect.com/security/oauth/device_verify?user_code=XPXI-F94U
homeconnect.0 | 2022-11-02 14:04:30.958 | error | Bitte überprüfe Benutzername und Passwort oder besuche diese Seite für manuelle Anmeldung:
homeconnect.0 | 2022-11-02 14:04:30.957 | error | Please check username and password or visit this site for manually login:
homeconnect.0 | 2022-11-02 14:04:30.957 | error | AxiosError: Request failed with status code 400
homeconnect.0 | 2022-11-02 14:04:20.829 | info | Wait 10 seconds to retry
homeconnect.0 | 2022-11-02 14:04:20.829 | error | {"error":"authorization_pending","error_description":"The authorization request is still pending as the end-user hasn't yet completed the user interaction steps"}
homeconnect.0 | 2022-11-02 14:04:20.829 | error | https://api.home-connect.com/security/oauth/device_verify?user_code=XPXI-F94U
homeconnect.0 | 2022-11-02 14:04:20.829 | error | Bitte überprüfe Benutzername und Passwort oder besuche diese Seite für manuelle Anmeldung:
homeconnect.0 | 2022-11-02 14:04:20.828 | error | Please check username and password or visit this site for manually login:
homeconnect.0 | 2022-11-02 14:04:20.828 | error | AxiosError: Request failed with status code 400
homeconnect.0 | 2022-11-02 14:04:10.716 | info | Wait 10 seconds to retry
homeconnect.0 | 2022-11-02 14:04:10.716 | error | {"error":"authorization_pending","error_description":"The authorization request is still pending as the end-user hasn't yet completed the user interaction steps"}
homeconnect.0 | 2022-11-02 14:04:10.716 | error | https://api.home-connect.com/security/oauth/device_verify?user_code=XPXI-F94U
homeconnect.0 | 2022-11-02 14:04:10.715 | error | Bitte überprüfe Benutzername und Passwort oder besuche diese Seite für manuelle Anmeldung:
homeconnect.0 | 2022-11-02 14:04:10.715 | error | Please check username and password or visit this site for manually login:
homeconnect.0 | 2022-11-02 14:04:10.714 | error | AxiosError: Request failed with status code 400
homeconnect.0 | 2022-11-02 14:04:04.417 | error | TypeError: Cannot read properties of undefined (reading '/auth/')
homeconnect.0 | 2022-11-02 14:04:04.417 | error | Please check username and password
homeconnect.0 | 2022-11-02 14:04:04.234 | info | Try new SingleKey Login
homeconnect.0 | 2022-11-02 14:04:04.233 | info | Normal Login response Your login details are incorrect, please check the information you entered.
homeconnect.0 | 2022-11-02 14:04:03.775 | info | starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v16.17.0, js-controller: 4.0.23
homeconnect.0 | 2022-11-02 14:03:59.425 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
homeconnect.0 | 2022-11-02 14:03:59.424 | info | terminating
homeconnect.0 | 2022-11-02 14:03:59.423 | info | Got terminate signal TERMINATE_YOURSELF
homeconnect.0 | 2022-11-02 14:03:59.413 | warn | State "homeconnect.0.dev.refreshToken" has no existing object, this might lead to an error in future versions
homeconnect.0 | 2022-11-02 14:03:59.359 | info | Reset access
homeconnect.0 | 2022-11-02 14:03:59.342 | info | starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v16.17.0, js-controller: 4.0.23


</body>
</html>

Wenn ich die URL: https://api.home-connect.com/security/oauth/device_verify?user_code=XPXI-F94U manuell im browser öffne kann ich die Verifikation abschließen. Der Adapter wird dann grün. Es werden aber keine Objekte abgerufen, außerdem kommen ständig Fehler im Log. Siehe oben.

**Comment by TA2k** [comment]
:"SDK.Error.504.GatewayTimeout scheint ein problem bei homeconnect zu sein einfach mal ein halben tag warten

**Comment by Heartblood76** [comment]
OK, jetzt funktioniert es wieder, Danke!

**Comment by shelly20222** [comment]
Ich habe auch das gleiche Problem. Es tut dann mal einen Tag (nach diesem manuellen einloggen) und dann wieder nicht. Aktuell ist das Gerät verbunden, aber im Protokoll kommt trotzdem ein Fehler:
<html><body>


homeconnect.0 | 2022-12-02 10:42:15.854 | info | SIEMENS-WT7WH540-xxx/programs/active: There is no program active.
-- | -- | -- | --
homeconnect.0 | 2022-12-02 10:42:15.745 | info | SIEMENS-WT7WH540-xxx/programs/active/options: There is no program active.
homeconnect.0 | 2022-12-02 10:42:14.217 | info | Found 1 devices
homeconnect.0 | 2022-12-02 10:42:14.040 | error | Start relogin in 10min
homeconnect.0 | 2022-12-02 10:42:14.040 | error | {"error":"invalid_client","error_description":"client has limited user list - user not assigned to client"}
homeconnect.0 | 2022-12-02 10:42:14.039 | error | AxiosError: Request failed with status code 401
homeconnect.0 | 2022-12-02 10:42:14.037 | error | refresh token failed


</body>
</html>

**Comment by shelly20222** [comment]
jetzt hab ich die manuelle Anmeldung gemacht und es schein erfolgreich zu sein. Der Adapter zeigt grün an:
<html><body>


homeconnect.0 | 2022-12-02 10:55:12.340 | info | Token received succesfully
-- | -- | -- | --
homeconnect.0 | 2022-12-02 10:55:02.244 | info | Wait 10 seconds to retry
homeconnect.0 | 2022-12-02 10:55:02.243 | error | {"error":"authorization_pending","error_description":"The  authorization request is still pending as the end-user hasn't yet  completed the user interaction steps"}
homeconnect.0 | 2022-12-02 10:55:02.242 | error | https://api.home-connect.com/security/oauth/device_verify?user_code=08US-R18F
homeconnect.0 | 2022-12-02 10:55:02.242 | error | Bitte überprüfe Benutzername und Passwort oder besuche diese Seite für manuelle Anmeldung:
homeconnect.0 | 2022-12-02 10:55:02.241 | error | Please check username and password or visit this site for manually login:
homeconnect.0 | 2022-12-02 10:55:02.240 | error | AxiosError: Request failed with status code 400
homeconnect.0 | 2022-12-02 10:54:52.153 | info | Wait 10 seconds to retry
homeconnect.0 | 2022-12-02 10:54:52.153 | error | {"error":"authorization_pending","error_description":"The  authorization request is still pending as the end-user hasn't yet  completed the user interaction steps"}
homeconnect.0 | 2022-12-02 10:54:52.152 | error | https://api.home-connect.com/security/oauth/device_verify?user_code=08US-R18F
homeconnect.0 | 2022-12-02 10:54:52.152 | error | Bitte überprüfe Benutzername und Passwort oder besuche diese Seite für manuelle Anmeldung:
homeconnect.0 | 2022-12-02 10:54:52.151 | error | Please check username and password or visit this site for manually login:
homeconnect.0 | 2022-12-02 10:54:52.150 | error | AxiosError: Request failed with status code 400


</body>
</html>

Aber es war schon ein paar mal so und am nächsten Tag geht das Spiel von vorne los. Ich halte euch auf dem laufenden...

**Comment by shelly20222** [comment]
darf man den Trockner eigentlich ausschalten oder muss man den ständig im WLAN lassen. Irgendwie nervt es: wenn man es hinbekommen hat funktionert es am nächsten Tag nicht mehr...

**Comment by TA2k** [comment]
Geräte können jederzeit ausgeschaltet werden und verbinden sich beim einschalten neu wenn die WLAN Qualität ausreichend ist

**Comment by shelly20222** [comment]
Ich habe den "Fehler" wohl gefunden. Es lag wohl daran, dass mein HomeConnect account "alt" war und sich das irgendwie mit dem SingleKey ID nicht vertragen hat. Habe dann einen neuen Home Connect Account mit dem Single Key ID angelegt und verbunden und diese im "Home Connect Developer Portal" als Default email for Home User account hinterlegt. Damit geht es jetzt :-)
