### ISSUE TITLE
Werte werden nicht upgedatet

### ISSUE THREAD

**Issue by Morluktom** [iobroker-community-adapters/ioBroker.homeconnect#5]
Hallo, 
mir ist folgendes Problem aufgefallen.
Folgende Datenpunkte werden bei mir manchmal nicht mehr upgedatet:
![image](https://user-images.githubusercontent.com/34573701/104807545-08641680-57e0-11eb-9c65-461d313d4863.png)

Der Grund ist da sich da von der API scheinbar die Uri ändert, denn ich finde dann die Datenpunkte unter selected:
![image](https://user-images.githubusercontent.com/34573701/104807594-655fcc80-57e0-11eb-9bc4-716f404b24ec.png)

Jetzt meine Frage, wäre es nicht sinnvoller den Adapter anhand des Keys aufzubauen, anstatt anhand der Uri?

**Comment by wired-ed** [comment]
+1

**Comment by n3ucr0n** [comment]
Selbes Problem habe ich beim Datenpunkt "Settings" - "Energiezustand" beobachtet.
Die Steuerung über den Datenpunkt (Ein- und Ausschalten des Gerätes) funktioniert noch, jedoch aktualisiert sich der Datenpunkt nicht. geht das Gerät von alleine aus oder wird via App / manuell am Gerät ausgeschaltet, verändert sich der Datenpunkt nicht.

![asdf](https://user-images.githubusercontent.com/63336916/105845506-22b9a380-5fdb-11eb-83ba-5479606a764a.JPG)

**Comment by Andr3asB** [comment]
Selbes Problem bei mir. Wir waschen/trocknen quasi täglich, aber 
- der Trockner hat seit 17 Tagen kein Update auf homeconnect.0.BOSCH-WTYH7781-[...].status.BSH_Common_Status_OperationState bekommen.
- die Waschmaschine seit drei Tagen kein Update auf homeconnect.0.BOSCH-WAX32E91-[...].status.BSH_Common_Status_OperationState 
Beide Geräte sind im Netzwerk und melden sich dort auch. Internetzugang ist enabled/Firewall ist offen, WLAN AP ist 3m entfernt, die HomeConnect-App funktioniert.
Der Geschirrspüler (homeconnect.0.BOSCH-SBE68TX26E-[...].status.BSH_Common_Status_OperationState) funktioniert seltsamer weise.

**Comment by Morluktom** [comment]
Welche Version des Adapter hast Du installiert?

**Comment by Andr3asB** [comment]
Der homeconnect adapter läuft bei mir auf 0.0.31. 
Node.js: v12.20.2
NPM: 6.14.11

**Comment by Morluktom** [comment]
Installiere die 0.0.32, dann wir genau dieses Verhalten besser.
