### ISSUE TITLE
Keine Anmeldung möglich

### ISSUE THREAD

**Issue by Instanz1** [iobroker-community-adapters/ioBroker.homeconnect#50]
Hallo,
ich habe heute versucht mich mit dem Adapter zu verbinden, leider erhalte ich immer folgende Meldung

`<html><body>

homeconnect.0 | 2022-12-04 15:58:51.723 | error | No verification_uri_complete in device_authorization
-- | -- | -- | --
homeconnect.0 | 2022-12-04 15:58:51.722 | error | "Illegal  query: Invalid input ' ', expected part, '&' or 'EOI' (line 1,  column 11): client_id=  95F1E9FB5A92B6FFCF508C745770475F91F133A57C6392FF792F112E05CC3166&scope=IdentifyAppliance%20Monitor%20Settings%20Control\n           ^"
homeconnect.0 | 2022-12-04 15:58:51.722 | error | AxiosError: Request failed with status code 400
homeconnect.0 | 2022-12-04 15:58:51.553 | info | starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v16.18.1, js-controller: 4.0.23

</body>
</html>`

Kann mir hier jemand weiterhelfen?

Die Tipps mit einem Passwort ohne Sonderzeichen gehen leider nicht, da die App von HomeConnect ein Sonderzeichen voraussetzen.

**Comment by TA2k** [comment]
Bitte das Leerzeichen vor der client id entfernen
