### ISSUE TITLE
Protokoll SPAM // Error Log im Iobroker // State value to set for ... has to be stringified but received type "number"

### ISSUE THREAD

**Issue by Knallix** [iobroker-community-adapters/ioBroker.homeconnect#51]
**Describe the bug**  
Der Error LOG wird beim verwenden über INFO vollgeschrieben

**To Reproduce**  
Es passiert beim Starten der Kaffeemaschine
SIEMENS-TI9555X1DE

**Screenshots & Logfiles**  
<html>
<body>

homeconnect.0 | 2022-12-09 13:49:55.404 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
-- | -- | -- | --
homeconnect.0 | 2022-12-09 13:49:54.404 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:53.408 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:52.465 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:52.247 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:52.243 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:51.951 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:51.942 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:51.930 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:51.403 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:49.410 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:48.406 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:43.403 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:42.403 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:41.401 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:40.432 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"
homeconnect.0 | 2022-12-09 13:49:39.401 | info | State value to set for "homeconnect.0.SIEMENS-TI9555X1DE-68A40E26FCF6.programs.active.options.BSH_Common_Option_ProgramProgress" has to be stringified but received type "number"

</body>
</html>

**Versions:**  
 - Adapter version: V1.1.1 <adapter-version>
 - JS-Controller version: 4.0.23  <js-controller-version> 
 - Node version: v14.19.3 
 - Operating system: Debian  <os-name>

**Comment by TA2k** [comment]
Datenpunkt löschen und adapter neustarten hilft hier
