### ISSUE TITLE
May wrong state config

### ISSUE THREAD

**Issue by fabiankrauss** [iobroker-community-adapters/ioBroker.homeconnect#55]
**Describe the bug**  
The log gives me times this message:
State value to set for "homeconnect.0.BOSCH-WAWH8640-XXXXXXXX.programs.active.options.BSH_Common_Option_RemainingProgramTime" has to be stringified but received type "number"

(replaced the Serialnumber with XXXXX)

**To Reproduce**  
1. Start the washing machine?
2. Wait

**Expected behavior**  
no info log?

**Versions:**  
 - Adapter version: 1.0.2
 - JS-Controller version:  4.0.23
 - Node version: v14.19.0 
 - Operating system: linux

**Comment by TA2k** [comment]
Objekt löschen und Adapter neustarten

**Comment by mcm1957** [comment]
If this problem still exists with current version, please reopen
