### ISSUE TITLE
Refresh Token failed / Invalid Client

### ISSUE THREAD

**Issue by Bernd9000** [iobroker-community-adapters/ioBroker.homeconnect#59]
Hab das Problem das der automatische token refresh nicht funktioniert.
Z.B. wenn der homeconnect Adapter neu gestartet wird.
Ich muss dann immer in den Haupteinstellungen den Haken bei Zugang/Token zurücksetzen anhacken.
Erst dann funktioniert es wieder.

IOB Log beim Adapter neustart:

homeconnect.0 | 2023-03-18 00:27:10.207 | error | Restart adapter in 20min
homeconnect.0 | 2023-03-18 00:27:10.207 | error | {"error":"invalid_client","error_description":"client has limited user list - user not assigned to client"}
homeconnect.0 | 2023-03-18 00:27:10.207 | error | AxiosError: Request failed with status code 401
homeconnect.0 | 2023-03-18 00:27:10.207 | error | refresh token failed

Bei manuellem Token refresh kriege ich folgende Warnung:

warn | State "homeconnect.0.dev.refreshToken" has no existing object, this might lead to an error in future versions

**Comment by TA2k** [comment]
Die Fehlermeldung klingt komisch vielleicht mal ein neuen account erstellen

**Comment by Bernd9000** [comment]
Ja, das war der richtige Tip, Danke.
Hab neuen Account und dann die App Freigabe neu erstellt, 
Jetzt läuft es wieder.
Könnte eventuell an einem Großbuchstaben in der E-Mail Adresse liegen, das hatte jemand schon mal aus einem anderen Forum gemeldet.
Ich mach mal dicht...
