### ISSUE TITLE
Fehlende Ordner bei Geschirrspühler und Waschmaschine

### ISSUE THREAD

**Issue by Airborne2010** [iobroker-community-adapters/ioBroker.homeconnect#6]
Hallo 
Bei meinem Geschirrspühler und der Waschmaschine wird nur der Ordner Commands und General, welcher leer ist, angezeigt. Bei dem Herd werden alle Ordner (settings usw) angezeigt.
Wäre super wenn jemand unterstützen könnte. In diesem Zustand lässt sich der Geschirrspühler nicht starten.

Vielen Dank

**Comment by TA2k** [comment]
Im eingeschalteten Zustand den Adapter neustarten?

**Comment by Morluktom** [comment]
Welche Version des Adapter hast Du?

**Comment by Airborne2010** [comment]
Vielen Dank für den Tip mit Einschalten und Adapter Neustart. Hat funktioniert. Habe die Version 0.0.31. Ich hoffe, ich muss den Adapter nicht jedesmal neu starten...

Der Fall kann geschlossen werden.

**Comment by Morluktom** [comment]
Installiere die 0.0.32. Mit der 0.0.31 hatte ich laufend Probleme das Geräte nicht gefunden wurden.

**Comment by Thomas-lab-cloud** [comment]
Hallo, ich habe die gleichen Probleme und bitte um Hilfe: wie kann ich denn die 0.0.32 installieren? ioBroker zeigt mir nur die 31 an. Danke.
