### ISSUE TITLE
HowTo install after end-of-live of Home Connect Plus?

### ISSUE THREAD

**Issue by oe8bck** [iobroker-community-adapters/ioBroker.homeconnect#60]
I just heard that the cloud service will be stopped soon:
https://www.heise.de/news/Smart-Home-Steuerungs-App-Home-Connect-Plus-wird-eingestellt-8188228.html

I am planning to buy some BSH devices and would like to integrate them in my ioBroker eco-system. How to do it when the service stopped?

**Comment by TA2k** [comment]
Correct the adapter use home connect api and not https://www.home-connect-plus.com/de/en/

**Comment by oe8bck** [comment]
For what reason do I need te ClientID? Is this because the API needs Internet access? What if - for whatever reason - I do not have an Internet access any more. Does the adapter stops working? (I did not check the API in detail)

**Comment by oe8bck** [comment]
In the meantime I've read the API dosumnetation. If I got it correctly, the API server is located in the "cloud" and all the communication is handled there. So this is not what I want for my smart home, maybe I should re-think about devices from BHS...

Thanks for your answers, this helped a lot!
