### ISSUE TITLE
Siemens WaMa - Unsupported Program Hygiene Plus

### ISSUE THREAD

**Issue by RoHo83** [iobroker-community-adapters/ioBroker.homeconnect#65]
Hi,
Der Fernstart meiner Waschmaschine funktioniert leider nicht mit allen Programmen und ich weiß nicht warum. 

Hier der Fehler aus dem IOBroker Log: 

{"error":{"description":"Unsupported operation: LaundryCare.Washer.Program.HygienePlus","key":"SDK.Error.UnsupportedProgram"}}

So wie ich das Verstehe kennt er das Programm HygienePlus nicht obwohl es als Object im IO Broker vorhanden ist. Was mich allerdings stutzig macht ist das das Programm nicht unter available zu finden ist sondern nur über selected. Allerdings verstehe ich auch den Unterschied der Objekte an dieser Stelle nicht. 

![image](https://github.com/iobroker-community-adapters/ioBroker.homeconnect/assets/137434475/1c532d79-36f9-4e1f-bc4e-2fddceadf78b)

Hier mein Setup in NodeRed - Damit funktioniert der Fernstart für andere Programme ohne Probleme:

![image](https://github.com/iobroker-community-adapters/ioBroker.homeconnect/assets/137434475/1f2c0c44-9590-41ba-96f1-2d9a18578ce8)

Hat jemand eine Idee?

Danke

**Comment by TA2k** [comment]
wenn es nicht unter available steht wird es vom homeconnect sdk unterstützt für support direkt an homeconnect wenden
https://developer.home-connect.com/support/contact
