### ISSUE TITLE
Warnmeldungen nach JS controller Update 3.2.16

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.homeconnect#8]
Hallo, folgende Warnmeldungen kommen im Log:

`homeconnect.0	2021-02-15 09:30:56.381	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.selected.options.Eco50.Dishcare_Dishwasher_Option_SilenceOnDemand" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:56.380	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.selected.options.Eco50.Dishcare_Dishwasher_Option_VarioSpeedPlus" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:56.378	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.selected.options.Eco50.Dishcare_Dishwasher_Option_IntensivZone" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:56.377	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.selected.options.Eco50.Dishcare_Dishwasher_Option_ExtraDry" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:56.376	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.selected.options.Eco50.BSH_Common_Option_StartInRelative" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:54.869	info	(10056) xxxxxxxxxxxxxxx: There is no program active
homeconnect.0	2021-02-15 09:30:51.843	info	(10056) xxxxxxxxxxxxxxx: There is no program active
homeconnect.0	2021-02-15 09:30:50.453	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.status.BSH_Common_Status_OperationState" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:50.453	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.status.BSH_Common_Status_DoorState" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:50.453	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.status.BSH_Common_Status_RemoteControlActive" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:50.453	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.status.BSH_Common_Status_RemoteControlStartAllowed" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:50.452	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.settings.BSH_Common_Setting_PowerState" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:50.452	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.available.Dishcare_Dishwasher_Program_MachineCare" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:50.452	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.available.Dishcare_Dishwasher_Program_Quick65" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:50.452	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.available.Dishcare_Dishwasher_Program_NightWash" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:50.451	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.available.Dishcare_Dishwasher_Program_Eco50" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:50.451	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.available.Dishcare_Dishwasher_Program_Auto2" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:50.450	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.programs.available.Dishcare_Dishwasher_Program_Intensiv70" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:49.478	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.events.BSH_Common_Event_ProgramFinished" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:47.198	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.general.haId" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:47.198	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.general.enumber" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:47.197	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.general.type" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:47.197	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.general.connected" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:47.196	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.general.vib" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:47.196	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.general.brand" has no existing object, this might lead to an error in future versions
homeconnect.0	2021-02-15 09:30:47.195	warn	(10056) State "homeconnect.0.xxxxxxxxxxxxxxx.general.name" has no existing object, this might lead to an error in future versions`

**Comment by OberfragGER** [comment]
das gleiche bei der Kaffeemaschine:
2021-02-16 15:04:25.839  - [33mwarn[39m: homeconnect.0 (9366) State "homeconnect.0.BOSCH-CTL636ES6-68A40E26C6C6.programs.active.options.ConsumerProducts_CoffeeMaker_Option_CoffeeTemperature" has no existing object, this might lead to an error in future versions
2021-02-16 15:04:25.840  - [33mwarn[39m: homeconnect.0 (9366) State "homeconnect.0.BOSCH-CTL636ES6-68A40E26C6C6.programs.active.options.ConsumerProducts_CoffeeMaker_Option_BeanAmount" has no existing object, this might lead to an error in future versions
2021-02-16 15:04:25.840  - [33mwarn[39m: homeconnect.0 (9366) State "homeconnect.0.BOSCH-CTL636ES6-68A40E26C6C6.programs.active.options.ConsumerProducts_CoffeeMaker_Option_FillQuantity" has no existing object, this might lead to an error in future versions
2021-02-16 15:04:25.840  - [33mwarn[39m: homeconnect.0 (9366) State "homeconnect.0.BOSCH-CTL636ES6-68A40E26C6C6.programs.active.options.ConsumerProducts_CoffeeMaker_Option_MultipleBeverages" has no existing object, this might lead to an error in future versions
