### ISSUE TITLE
Update für die TQ9, Fehlermeldung beim start.

### ISSUE THREAD

**Issue by zaphod2** [iobroker-community-adapters/ioBroker.homeconnect#93]
Die Kaffeemaschine hat ein update bekommen und seid dem kommen beim Start des Adapters folgende Fehlermeldungen. Es ist aber alles soweit nutzbar und die Meldungen kommen nur 1 mal beim Adapterstart.

`{"data":{"active":{"constraints":{"access":"read"},"key":"ConsumerProducts.CoffeeMaker.Program.CleaningModes.Clean","name":"Reinigen","options":[{"key":"BSH.Common.Option.ProgramProgress","value":77,"unit":"%","name":"aktueller Programmfortschritt"},{"key":"BSH.Common.Option.EstimatedTotalProgramTime","value":540,"unit":"seconds","name":"Geschätzte Gesamtprogrammlaufzeit"},{"key":"ConsumerProducts.CoffeeMaker.Option.BeveragesRemaining","value":0,"name":"verbleibende Getränke"},{"key":"BSH.Common.Option.EstimatedCurrentStepTime","value":480,"unit":"seconds","name":"Geschätzte Zeit Prozessschritt"}]},"programs":[{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.Espresso","name":"Espresso"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.EspressoDoppio","name":"Espresso doppio"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.Coffee","name":"Caffè Crema"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.CaffeGrande","name":"Caffè Grande"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.XLCoffee","name":"Caffè XL"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.Cappuccino","name":"Cappuccino"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.LatteMacchiato","name":"Latte macchiato"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.CaffeLatte","name":"Milchkaffee"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.MilkFroth","name":"Milchschaum"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.WarmMilk","name":"Warme Milch"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.HotWater","name":"Heißwasser"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.Ristretto","name":"Ristretto"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.EspressoMacchiato","name":"Espresso macchiato"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Verlaengerter","name":"Verlängerter"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.KleinerBrauner","name":"Kleiner Brauner"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.WienerMelange","name":"Wiener Melange"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.FlatWhite","name":"Flat white"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.CafeConLeche","name":"Café con leche"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.CafeAuLait","name":"Café au lait"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.KoffieVerkeerd","name":"Koffie verkeerd"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Americano","name":"Americano"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.GrosserBrauner","name":"Großer Brauner"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.VerlaengerterBraun","name":"Verlängerter braun"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Cortado","name":"Cortado"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Doppio","name":"Doppio"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.CafeCortado","name":"Café cortado"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Kaapi","name":"Kaapi"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Galao","name":"Galão"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Garoto","name":"Garoto"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.RedEye","name":"Red eye"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.BlackEye","name":"Black eye"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.DeadEye","name":"Dead eye"}],"selected":{"constraints":{"access":"read"},"key":"ConsumerProducts.CoffeeMaker.Program.CleaningModes.Clean","name":"Reinigen","options":[{"key":"BSH.Common.Option.EstimatedTotalProgramTime","value":540,"unit":"seconds","name":"Geschätzte Gesamtprogrammlaufzeit"},{"key":"ConsumerProducts.CoffeeMaker.Option.BeveragesRemaining","value":0,"name":"verbleibende Getränke"},{"key":"BSH.Common.Option.EstimatedCurrentStepTime","value":480,"unit":"seconds","name":"Geschätzte Zeit Prozessschritt"}]}}}`

`/programs`

`TypeError: returnValue.data[item].forEach is not a function at Homeconnect.getAPIValues (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:573:32) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

`TypeError: returnValue.data[item].forEach is not a function`

**Comment by mcm1957** [comment]
Bitte bei Issues immer die entsprechenden Versionen angeben

Adapter
js-controler
Node
O/S

**Comment by zaphod2** [comment]
> Adapter     1.1.1
> js-controler    5.0.12
> Node    18.18.2
> O/S    debian 12

**Comment by TA2k** [comment]
Hat die GitHub version das gleiche verhalten?

**Comment by zaphod2** [comment]
Ja

**Comment by TA2k** [comment]
Also der Fehler sollte zumindest anders jetzt sein

**Comment by zaphod2** [comment]
<html>
<body>


{"data":{"active":{"constraints":{"access":"read"}},"programs":[{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.Espresso","name":"Espresso"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.EspressoDoppio","name":"Espresso doppio"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.Coffee","name":"Caffè Crema"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.CaffeGrande","name":"Caffè Grande"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.XLCoffee","name":"Caffè XL"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.Cappuccino","name":"Cappuccino"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.LatteMacchiato","name":"Latte macchiato"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.CaffeLatte","name":"Milchkaffee"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.MilkFroth","name":"Milchschaum"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.WarmMilk","name":"Warme Milch"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.HotWater","name":"Heißwasser"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.Ristretto","name":"Ristretto"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.Beverage.EspressoMacchiato","name":"Espresso macchiato"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Verlaengerter","name":"Verlängerter"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.KleinerBrauner","name":"Kleiner Brauner"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.WienerMelange","name":"Wiener Melange"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.FlatWhite","name":"Flat white"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.CafeConLeche","name":"Café con leche"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.CafeAuLait","name":"Café au lait"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.KoffieVerkeerd","name":"Koffie verkeerd"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Americano","name":"Americano"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.GrosserBrauner","name":"Großer Brauner"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.VerlaengerterBraun","name":"Verlängerter braun"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Cortado","name":"Cortado"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Doppio","name":"Doppio"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.CafeCortado","name":"Café cortado"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Kaapi","name":"Kaapi"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Galao","name":"Galão"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Garoto","name":"Garoto"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.RedEye","name":"Red eye"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.BlackEye","name":"Black eye"},{"constraints":{"available":true,"execution":"selectandstart"},"key":"ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.DeadEye","name":"Dead eye"}],"selected":{"constraints":{"access":"read"},"key":"BSH.Common.Program.Favorite.001","name":"Favorit","options":[{"key":"BSH.Common.Option.ProgramName","value":"Torsten: Latte macchiato"},{"key":"BSH.Common.Option.BaseProgram","value":"ConsumerProducts.CoffeeMaker.Program.Beverage.LatteMacchiato","displayvalue":"Latte macchiato"},{"key":"ConsumerProducts.CoffeeMaker.Option.CoffeeStrength","value":"ConsumerProducts.CoffeeMaker.EnumType.CoffeeStrength.Strength5","name":"Stärke","displayvalue":"5"},{"key":"ConsumerProducts.CoffeeMaker.Option.FillQuantity","value":325,"unit":"ml","name":"Menge"},{"key":"ConsumerProducts.CoffeeMaker.Option.CoffeeMilkRatio","value":"ConsumerProducts.CoffeeMaker.EnumType.CoffeeMilkRatio.80Percent","name":"Milchanteil","displayvalue":"80%"},{"key":"ConsumerProducts.CoffeeMaker.Option.MultipleBeverages","value":false,"name":"Doppelbezug"},{"key":"ConsumerProducts.CoffeeMaker.Option.FlowRate","value":"ConsumerProducts.CoffeeMaker.EnumType.FlowRate.IntensePlus","name":"Kontaktzeit","displayvalue":"lang"},{"key":"ConsumerProducts.CoffeeMaker.Option.CoffeeTemperature","value":"ConsumerProducts.CoffeeMaker.EnumType.CoffeeTemperature.98C","name":"Temperatur","displayvalue":"98°C"},{"key":"ConsumerProducts.CoffeeMaker.Option.Coarsness","value":"ConsumerProducts.CoffeeMaker.EnumType.CoarsnessExtended.Coarsness1","name":"Mahlgrad","displayvalue":"1/6"}]}}}
--
homeconnect.0 | 2023-11-09 19:46:09.287 | error | /programs
homeconnect.0 | 2023-11-09 19:46:09.286 | error | TypeError: returnValue.data[item] is not iterable at Homeconnect.getAPIValues (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:577:50) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
homeconnect.0 | 2023-11-09 19:46:09.286 | error | TypeError: returnValue.data[item] is not iterable


</body>
</html>

**Comment by TA2k** [comment]
probier nochmal wie es sich jetzt verhält

**Comment by zaphod2** [comment]
na toll, jetzt kommt alle 20 sec. 

host.IoBroker | 2023-11-09 20:13:14.530 | error | instance system.adapter.homeconnect.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.IoBroker | 2023-11-09 20:13:14.530 | error | Caught by controller[0]: Node.js v18.18.2
host.IoBroker | 2023-11-09 20:13:14.530 | error | Caught by controller[0]: at node:internal/main/run_main_module:23:47
host.IoBroker | 2023-11-09 20:13:14.530 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
host.IoBroker | 2023-11-09 20:13:14.529 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:960:12)
host.IoBroker | 2023-11-09 20:13:14.529 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1119:32)
host.IoBroker | 2023-11-09 20:13:14.529 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.IoBroker | 2023-11-09 20:13:14.529 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1220:27)
host.IoBroker | 2023-11-09 20:13:14.529 | error | Caught by controller[0]: at wrapSafe (node:internal/modules/cjs/loader:1178:20)
host.IoBroker | 2023-11-09 20:13:14.529 | error | Caught by controller[0]: at internalCompileFunction (node:internal/vm:73:18)
host.IoBroker | 2023-11-09 20:13:14.529 | error | Caught by controller[0]: SyntaxError: Unexpected token 'catch'
host.IoBroker | 2023-11-09 20:13:14.529 | error | Caught by controller[0]: ^^^^^
host.IoBroker | 2023-11-09 20:13:14.529 | error | Caught by controller[0]: } catch (error) {
host.IoBroker | 2023-11-09 20:13:14.529 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.homeconnect/main.js:727

**Comment by zaphod2** [comment]
Adapter wird nicht mehr grün

**Comment by TA2k** [comment]
Dann nochmal

**Comment by zaphod2** [comment]
Super, das ging ja schnell. Scheint jetzt zu laufen.

**Comment by TA2k** [comment]
Bittte testen ob selected programme ordentlich angezeigt werden und funktionieren

**Comment by zaphod2** [comment]
Ich kann jetzt nichts nachteiliges erkenne.
